// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	HDNodeType
	HDNodePathType
	CoinType
	MultisigRedeemScriptType
	TxInputType
	TxOutputType
	TxOutputBinType
	TransactionType
	RawTransactionType
	TxRequestDetailsType
	TxRequestSerializedType
	IdentityType
	PolicyType
	ExchangeType
*/
package types

import (
	fmt "fmt"
	"strconv"

	proto "github.com/golang/protobuf/proto"

	math "math"

	google_protobuf "github.com/conejoninja/cerrojo/pb/google/protobuf"

	"github.com/conejoninja/cerrojo/pb/exchange"
	types "github.com/conejoninja/cerrojo/pb/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Type of failures returned by Failure message
// @used_in Failure
type FailureType int32

const (
	FailureType_Failure_UnexpectedMessage FailureType = 1
	FailureType_Failure_ButtonExpected    FailureType = 2
	FailureType_Failure_SyntaxError       FailureType = 3
	FailureType_Failure_ActionCancelled   FailureType = 4
	FailureType_Failure_PinExpected       FailureType = 5
	FailureType_Failure_PinCancelled      FailureType = 6
	FailureType_Failure_PinInvalid        FailureType = 7
	FailureType_Failure_InvalidSignature  FailureType = 8
	FailureType_Failure_Other             FailureType = 9
	FailureType_Failure_NotEnoughFunds    FailureType = 10
	FailureType_Failure_NotInitialized    FailureType = 11
	FailureType_Failure_FirmwareError     FailureType = 99
)

var FailureType_name = map[int32]string{
	1:  "Failure_UnexpectedMessage",
	2:  "Failure_ButtonExpected",
	3:  "Failure_SyntaxError",
	4:  "Failure_ActionCancelled",
	5:  "Failure_PinExpected",
	6:  "Failure_PinCancelled",
	7:  "Failure_PinInvalid",
	8:  "Failure_InvalidSignature",
	9:  "Failure_Other",
	10: "Failure_NotEnoughFunds",
	11: "Failure_NotInitialized",
	99: "Failure_FirmwareError",
}
var FailureType_value = map[string]int32{
	"Failure_UnexpectedMessage": 1,
	"Failure_ButtonExpected":    2,
	"Failure_SyntaxError":       3,
	"Failure_ActionCancelled":   4,
	"Failure_PinExpected":       5,
	"Failure_PinCancelled":      6,
	"Failure_PinInvalid":        7,
	"Failure_InvalidSignature":  8,
	"Failure_Other":             9,
	"Failure_NotEnoughFunds":    10,
	"Failure_NotInitialized":    11,
	"Failure_FirmwareError":     99,
}

func (x FailureType) Enum() *FailureType {
	p := new(FailureType)
	*p = x
	return p
}
func (x FailureType) String() string {
	return proto.EnumName(FailureType_name, int32(x))
}
func (x *FailureType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FailureType_value, data, "FailureType")
	if err != nil {
		return err
	}
	*x = FailureType(value)
	return nil
}
func (FailureType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Type of script which will be used for transaction output
// @used_in TxOutputType
type OutputScriptType int32

const (
	OutputScriptType_PAYTOADDRESS     OutputScriptType = 0
	OutputScriptType_PAYTOSCRIPTHASH  OutputScriptType = 1
	OutputScriptType_PAYTOMULTISIG    OutputScriptType = 2
	OutputScriptType_PAYTOOPRETURN    OutputScriptType = 3
	OutputScriptType_PAYTOWITNESS     OutputScriptType = 4
	OutputScriptType_PAYTOP2SHWITNESS OutputScriptType = 5
)

var OutputScriptType_name = map[int32]string{
	0: "PAYTOADDRESS",
	1: "PAYTOSCRIPTHASH",
	2: "PAYTOMULTISIG",
	3: "PAYTOOPRETURN",
	4: "PAYTOWITNESS",
	5: "PAYTOP2SHWITNESS",
}
var OutputScriptType_value = map[string]int32{
	"PAYTOADDRESS":     0,
	"PAYTOSCRIPTHASH":  1,
	"PAYTOMULTISIG":    2,
	"PAYTOOPRETURN":    3,
	"PAYTOWITNESS":     4,
	"PAYTOP2SHWITNESS": 5,
}

func (x OutputScriptType) Enum() *OutputScriptType {
	p := new(OutputScriptType)
	*p = x
	return p
}
func (x OutputScriptType) String() string {
	return proto.EnumName(OutputScriptType_name, int32(x))
}
func (x *OutputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputScriptType_value, data, "OutputScriptType")
	if err != nil {
		return err
	}
	*x = OutputScriptType(value)
	return nil
}
func (OutputScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
// Type of script which will be used for transaction output
// @used_in TxInputType
type InputScriptType int32

const (
	InputScriptType_SPENDADDRESS     InputScriptType = 0
	InputScriptType_SPENDMULTISIG    InputScriptType = 1
	InputScriptType_EXTERNAL         InputScriptType = 2
	InputScriptType_SPENDWITNESS     InputScriptType = 3
	InputScriptType_SPENDP2SHWITNESS InputScriptType = 4
)

var InputScriptType_name = map[int32]string{
	0: "SPENDADDRESS",
	1: "SPENDMULTISIG",
	2: "EXTERNAL",
	3: "SPENDWITNESS",
	4: "SPENDP2SHWITNESS",
}
var InputScriptType_value = map[string]int32{
	"SPENDADDRESS":     0,
	"SPENDMULTISIG":    1,
	"EXTERNAL":         2,
	"SPENDWITNESS":     3,
	"SPENDP2SHWITNESS": 4,
}

func (x InputScriptType) Enum() *InputScriptType {
	p := new(InputScriptType)
	*p = x
	return p
}
func (x InputScriptType) String() string {
	return proto.EnumName(InputScriptType_name, int32(x))
}
func (x *InputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InputScriptType_value, data, "InputScriptType")
	if err != nil {
		return err
	}
	*x = InputScriptType(value)
	return nil
}
func (InputScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// *
// Type of information required by transaction signing process
// @used_in TxRequest
type RequestType int32

const (
	RequestType_TXINPUT     RequestType = 0
	RequestType_TXOUTPUT    RequestType = 1
	RequestType_TXMETA      RequestType = 2
	RequestType_TXFINISHED  RequestType = 3
	RequestType_TXEXTRADATA RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "TXINPUT",
	1: "TXOUTPUT",
	2: "TXMETA",
	3: "TXFINISHED",
	4: "TXEXTRADATA",
}
var RequestType_value = map[string]int32{
	"TXINPUT":     0,
	"TXOUTPUT":    1,
	"TXMETA":      2,
	"TXFINISHED":  3,
	"TXEXTRADATA": 4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// *
// Type of ouput address specify in transaction
// @used_in TxOutputType
type OutputAddressType int32

const (
	OutputAddressType_SPEND    OutputAddressType = 0
	OutputAddressType_TRANSFER OutputAddressType = 1
	OutputAddressType_CHANGE   OutputAddressType = 2
	OutputAddressType_EXCHANGE OutputAddressType = 3
)

var OutputAddressType_name = map[int32]string{
	0: "SPEND",
	1: "TRANSFER",
	2: "CHANGE",
	3: "EXCHANGE",
}
var OutputAddressType_value = map[string]int32{
	"SPEND":    0,
	"TRANSFER": 1,
	"CHANGE":   2,
	"EXCHANGE": 3,
}

func (x OutputAddressType) Enum() *OutputAddressType {
	p := new(OutputAddressType)
	*p = x
	return p
}
func (x OutputAddressType) String() string {
	return proto.EnumName(OutputAddressType_name, int32(x))
}
func (x *OutputAddressType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputAddressType_value, data, "OutputAddressType")
	if err != nil {
		return err
	}
	*x = OutputAddressType(value)
	return nil
}
func (OutputAddressType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// *
// Type of button request
// @used_in ButtonRequest
type ButtonRequestType int32

const (
	ButtonRequestType_ButtonRequest_Other                     ButtonRequestType = 1
	ButtonRequestType_ButtonRequest_FeeOverThreshold          ButtonRequestType = 2
	ButtonRequestType_ButtonRequest_ConfirmOutput             ButtonRequestType = 3
	ButtonRequestType_ButtonRequest_ResetDevice               ButtonRequestType = 4
	ButtonRequestType_ButtonRequest_ConfirmWord               ButtonRequestType = 5
	ButtonRequestType_ButtonRequest_WipeDevice                ButtonRequestType = 6
	ButtonRequestType_ButtonRequest_ProtectCall               ButtonRequestType = 7
	ButtonRequestType_ButtonRequest_SignTx                    ButtonRequestType = 8
	ButtonRequestType_ButtonRequest_FirmwareCheck             ButtonRequestType = 9
	ButtonRequestType_ButtonRequest_Address                   ButtonRequestType = 10
	ButtonRequestType_ButtonRequest_FirmwareErase             ButtonRequestType = 11
	ButtonRequestType_ButtonRequest_ConfirmTransferToAccount  ButtonRequestType = 12
	ButtonRequestType_ButtonRequest_ConfirmTransferToNodePath ButtonRequestType = 13
	ButtonRequestType_ButtonRequest_ChangeLabel               ButtonRequestType = 14
	ButtonRequestType_ButtonRequest_ChangeLanguage            ButtonRequestType = 15
	ButtonRequestType_ButtonRequest_EnablePassphrase          ButtonRequestType = 16
	ButtonRequestType_ButtonRequest_DisablePassphrase         ButtonRequestType = 17
	ButtonRequestType_ButtonRequest_EncryptAndSignMessage     ButtonRequestType = 18
	ButtonRequestType_ButtonRequest_EncryptMessage            ButtonRequestType = 19
	ButtonRequestType_ButtonRequest_ImportPrivateKey          ButtonRequestType = 20
	ButtonRequestType_ButtonRequest_ImportRecoverySentence    ButtonRequestType = 21
	ButtonRequestType_ButtonRequest_SignIdentity              ButtonRequestType = 22
	ButtonRequestType_ButtonRequest_Ping                      ButtonRequestType = 23
	ButtonRequestType_ButtonRequest_RemovePin                 ButtonRequestType = 24
	ButtonRequestType_ButtonRequest_ChangePin                 ButtonRequestType = 25
	ButtonRequestType_ButtonRequest_CreatePin                 ButtonRequestType = 26
	ButtonRequestType_ButtonRequest_GetEntropy                ButtonRequestType = 27
	ButtonRequestType_ButtonRequest_SignMessage               ButtonRequestType = 28
	ButtonRequestType_ButtonRequest_ApplyPolicies             ButtonRequestType = 29
	ButtonRequestType_ButtonRequest_SignExchange              ButtonRequestType = 30
)

var ButtonRequestType_name = map[int32]string{
	1:  "ButtonRequest_Other",
	2:  "ButtonRequest_FeeOverThreshold",
	3:  "ButtonRequest_ConfirmOutput",
	4:  "ButtonRequest_ResetDevice",
	5:  "ButtonRequest_ConfirmWord",
	6:  "ButtonRequest_WipeDevice",
	7:  "ButtonRequest_ProtectCall",
	8:  "ButtonRequest_SignTx",
	9:  "ButtonRequest_FirmwareCheck",
	10: "ButtonRequest_Address",
	11: "ButtonRequest_FirmwareErase",
	12: "ButtonRequest_ConfirmTransferToAccount",
	13: "ButtonRequest_ConfirmTransferToNodePath",
	14: "ButtonRequest_ChangeLabel",
	15: "ButtonRequest_ChangeLanguage",
	16: "ButtonRequest_EnablePassphrase",
	17: "ButtonRequest_DisablePassphrase",
	18: "ButtonRequest_EncryptAndSignMessage",
	19: "ButtonRequest_EncryptMessage",
	20: "ButtonRequest_ImportPrivateKey",
	21: "ButtonRequest_ImportRecoverySentence",
	22: "ButtonRequest_SignIdentity",
	23: "ButtonRequest_Ping",
	24: "ButtonRequest_RemovePin",
	25: "ButtonRequest_ChangePin",
	26: "ButtonRequest_CreatePin",
	27: "ButtonRequest_GetEntropy",
	28: "ButtonRequest_SignMessage",
	29: "ButtonRequest_ApplyPolicies",
	30: "ButtonRequest_SignExchange",
}
var ButtonRequestType_value = map[string]int32{
	"ButtonRequest_Other":                     1,
	"ButtonRequest_FeeOverThreshold":          2,
	"ButtonRequest_ConfirmOutput":             3,
	"ButtonRequest_ResetDevice":               4,
	"ButtonRequest_ConfirmWord":               5,
	"ButtonRequest_WipeDevice":                6,
	"ButtonRequest_ProtectCall":               7,
	"ButtonRequest_SignTx":                    8,
	"ButtonRequest_FirmwareCheck":             9,
	"ButtonRequest_Address":                   10,
	"ButtonRequest_FirmwareErase":             11,
	"ButtonRequest_ConfirmTransferToAccount":  12,
	"ButtonRequest_ConfirmTransferToNodePath": 13,
	"ButtonRequest_ChangeLabel":               14,
	"ButtonRequest_ChangeLanguage":            15,
	"ButtonRequest_EnablePassphrase":          16,
	"ButtonRequest_DisablePassphrase":         17,
	"ButtonRequest_EncryptAndSignMessage":     18,
	"ButtonRequest_EncryptMessage":            19,
	"ButtonRequest_ImportPrivateKey":          20,
	"ButtonRequest_ImportRecoverySentence":    21,
	"ButtonRequest_SignIdentity":              22,
	"ButtonRequest_Ping":                      23,
	"ButtonRequest_RemovePin":                 24,
	"ButtonRequest_ChangePin":                 25,
	"ButtonRequest_CreatePin":                 26,
	"ButtonRequest_GetEntropy":                27,
	"ButtonRequest_SignMessage":               28,
	"ButtonRequest_ApplyPolicies":             29,
	"ButtonRequest_SignExchange":              30,
}

func (x ButtonRequestType) Enum() *ButtonRequestType {
	p := new(ButtonRequestType)
	*p = x
	return p
}
func (x ButtonRequestType) String() string {
	return proto.EnumName(ButtonRequestType_name, int32(x))
}
func (x *ButtonRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ButtonRequestType_value, data, "ButtonRequestType")
	if err != nil {
		return err
	}
	*x = ButtonRequestType(value)
	return nil
}
func (ButtonRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// *
// Type of PIN request
// @used_in PinMatrixRequest
type PinMatrixRequestType int32

const (
	PinMatrixRequestType_PinMatrixRequestType_Current   PinMatrixRequestType = 1
	PinMatrixRequestType_PinMatrixRequestType_NewFirst  PinMatrixRequestType = 2
	PinMatrixRequestType_PinMatrixRequestType_NewSecond PinMatrixRequestType = 3
)

var PinMatrixRequestType_name = map[int32]string{
	1: "PinMatrixRequestType_Current",
	2: "PinMatrixRequestType_NewFirst",
	3: "PinMatrixRequestType_NewSecond",
}
var PinMatrixRequestType_value = map[string]int32{
	"PinMatrixRequestType_Current":   1,
	"PinMatrixRequestType_NewFirst":  2,
	"PinMatrixRequestType_NewSecond": 3,
}

func (x PinMatrixRequestType) Enum() *PinMatrixRequestType {
	p := new(PinMatrixRequestType)
	*p = x
	return p
}
func (x PinMatrixRequestType) String() string {
	return proto.EnumName(PinMatrixRequestType_name, int32(x))
}
func (x *PinMatrixRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PinMatrixRequestType_value, data, "PinMatrixRequestType")
	if err != nil {
		return err
	}
	*x = PinMatrixRequestType(value)
	return nil
}
func (PinMatrixRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// *
// Structure representing BIP32 (hierarchical deterministic) node
// Used for imports of private key into the device and exporting public key out of device
// @used_in PublicKey
// @used_in LoadDevice
// @used_in DebugLinkState
// @used_in Storage
type HDNodeType struct {
	Depth            *uint32 `protobuf:"varint,1,req,name=depth" json:"depth,omitempty"`
	Fingerprint      *uint32 `protobuf:"varint,2,req,name=fingerprint" json:"fingerprint,omitempty"`
	ChildNum         *uint32 `protobuf:"varint,3,req,name=child_num,json=childNum" json:"child_num,omitempty"`
	ChainCode        []byte  `protobuf:"bytes,4,req,name=chain_code,json=chainCode" json:"chain_code,omitempty"`
	PrivateKey       []byte  `protobuf:"bytes,5,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,6,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HDNodeType) Reset()                    { *m = HDNodeType{} }
func (m *HDNodeType) String() string            { return proto.CompactTextString(m) }
func (*HDNodeType) ProtoMessage()               {}
func (*HDNodeType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HDNodeType) GetDepth() uint32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *HDNodeType) GetFingerprint() uint32 {
	if m != nil && m.Fingerprint != nil {
		return *m.Fingerprint
	}
	return 0
}

func (m *HDNodeType) GetChildNum() uint32 {
	if m != nil && m.ChildNum != nil {
		return *m.ChildNum
	}
	return 0
}

func (m *HDNodeType) GetChainCode() []byte {
	if m != nil {
		return m.ChainCode
	}
	return nil
}

func (m *HDNodeType) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *HDNodeType) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type HDNodePathType struct {
	Node             *HDNodeType `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	AddressN         []uint32    `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *HDNodePathType) Reset()                    { *m = HDNodePathType{} }
func (m *HDNodePathType) String() string            { return proto.CompactTextString(m) }
func (*HDNodePathType) ProtoMessage()               {}
func (*HDNodePathType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HDNodePathType) GetNode() types.HDNodeTyper {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HDNodePathType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

// *
// Structure representing Coin
// @used_in Features
type CoinType struct {
	CoinName            *string `protobuf:"bytes,1,opt,name=coin_name,json=coinName" json:"coin_name,omitempty"`
	CoinShortcut        *string `protobuf:"bytes,2,opt,name=coin_shortcut,json=coinShortcut" json:"coin_shortcut,omitempty"`
	AddressType         *uint32 `protobuf:"varint,3,opt,name=address_type,json=addressType,def=0" json:"address_type,omitempty"`
	MaxfeeKb            *uint64 `protobuf:"varint,4,opt,name=maxfee_kb,json=maxfeeKb" json:"maxfee_kb,omitempty"`
	AddressTypeP2Sh     *uint32 `protobuf:"varint,5,opt,name=address_type_p2sh,json=addressTypeP2sh,def=5" json:"address_type_p2sh,omitempty"`
	AddressTypeP2Wpkh   *uint32 `protobuf:"varint,6,opt,name=address_type_p2wpkh,json=addressTypeP2wpkh,def=6" json:"address_type_p2wpkh,omitempty"`
	AddressTypeP2Wsh    *uint32 `protobuf:"varint,7,opt,name=address_type_p2wsh,json=addressTypeP2wsh,def=10" json:"address_type_p2wsh,omitempty"`
	SignedMessageHeader *string `protobuf:"bytes,8,opt,name=signed_message_header,json=signedMessageHeader" json:"signed_message_header,omitempty"`
	Bip44AccountPath    *uint32 `protobuf:"varint,9,opt,name=bip44_account_path,json=bip44AccountPath" json:"bip44_account_path,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CoinType) Reset()                    { *m = CoinType{} }
func (m *CoinType) String() string            { return proto.CompactTextString(m) }
func (*CoinType) ProtoMessage()               {}
func (*CoinType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_CoinType_AddressType uint32 = 0
const Default_CoinType_AddressTypeP2Sh uint32 = 5
const Default_CoinType_AddressTypeP2Wpkh uint32 = 6
const Default_CoinType_AddressTypeP2Wsh uint32 = 10

func (m *CoinType) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return ""
}

func (m *CoinType) GetCoinShortcut() string {
	if m != nil && m.CoinShortcut != nil {
		return *m.CoinShortcut
	}
	return ""
}

func (m *CoinType) GetAddressType() uint32 {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return Default_CoinType_AddressType
}

func (m *CoinType) GetMaxfeeKb() uint64 {
	if m != nil && m.MaxfeeKb != nil {
		return *m.MaxfeeKb
	}
	return 0
}

func (m *CoinType) GetAddressTypeP2Sh() uint32 {
	if m != nil && m.AddressTypeP2Sh != nil {
		return *m.AddressTypeP2Sh
	}
	return Default_CoinType_AddressTypeP2Sh
}

func (m *CoinType) GetAddressTypeP2Wpkh() uint32 {
	if m != nil && m.AddressTypeP2Wpkh != nil {
		return *m.AddressTypeP2Wpkh
	}
	return Default_CoinType_AddressTypeP2Wpkh
}

func (m *CoinType) GetAddressTypeP2Wsh() uint32 {
	if m != nil && m.AddressTypeP2Wsh != nil {
		return *m.AddressTypeP2Wsh
	}
	return Default_CoinType_AddressTypeP2Wsh
}

func (m *CoinType) GetSignedMessageHeader() string {
	if m != nil && m.SignedMessageHeader != nil {
		return *m.SignedMessageHeader
	}
	return ""
}

func (m *CoinType) GetBip44AccountPath() uint32 {
	if m != nil && m.Bip44AccountPath != nil {
		return *m.Bip44AccountPath
	}
	return 0
}

// *
// Type of redeem script used in input
// @used_in TxInputType
type MultisigRedeemScriptType struct {
	Pubkeys          []*HDNodePathType `protobuf:"bytes,1,rep,name=pubkeys" json:"pubkeys,omitempty"`
	Signatures       [][]byte          `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
	M                *uint32           `protobuf:"varint,3,opt,name=m" json:"m,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MultisigRedeemScriptType) Reset()                    { *m = MultisigRedeemScriptType{} }
func (m *MultisigRedeemScriptType) String() string            { return proto.CompactTextString(m) }
func (*MultisigRedeemScriptType) ProtoMessage()               {}
func (*MultisigRedeemScriptType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MultisigRedeemScriptType) GetPubkeys() []types.HDNodePathTyper {
	if m != nil {
		l := len(m.Pubkeys)
		z := make([]types.HDNodePathTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.Pubkeys[i]
		}
		return z
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetM() uint32 {
	if m != nil && m.M != nil {
		return *m.M
	}
	return 0
}

// *
// Structure representing transaction input
// @used_in SimpleSignTx
// @used_in TransactionType
type TxInputType struct {
	AddressN         []uint32                  `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	PrevHash         []byte                    `protobuf:"bytes,2,req,name=prev_hash,json=prevHash" json:"prev_hash,omitempty"`
	PrevIndex        *uint32                   `protobuf:"varint,3,req,name=prev_index,json=prevIndex" json:"prev_index,omitempty"`
	ScriptSig        []byte                    `protobuf:"bytes,4,opt,name=script_sig,json=scriptSig" json:"script_sig,omitempty"`
	Sequence         *uint32                   `protobuf:"varint,5,opt,name=sequence,def=4294967295" json:"sequence,omitempty"`
	ScriptType       *InputScriptType          `protobuf:"varint,6,opt,name=script_type,json=scriptType,enum=InputScriptType,def=0" json:"script_type,omitempty"`
	Multisig         *MultisigRedeemScriptType `protobuf:"bytes,7,opt,name=multisig" json:"multisig,omitempty"`
	Amount           *uint64                   `protobuf:"varint,8,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *TxInputType) Reset()                    { *m = TxInputType{} }
func (m *TxInputType) String() string            { return proto.CompactTextString(m) }
func (*TxInputType) ProtoMessage()               {}
func (*TxInputType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_TxInputType_Sequence uint32 = 4294967295
const Default_TxInputType_ScriptType InputScriptType = InputScriptType_SPENDADDRESS

func (m *TxInputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxInputType) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *TxInputType) GetPrevIndex() uint32 {
	if m != nil && m.PrevIndex != nil {
		return *m.PrevIndex
	}
	return 0
}

func (m *TxInputType) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

func (m *TxInputType) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return Default_TxInputType_Sequence
}

func (m *TxInputType) GetScriptType() types.InputScriptTyper {
	if m != nil && m.ScriptType != nil {
		return m.ScriptType
	}
	x := InputScriptType(Default_TxInputType_ScriptType)
	return &x
}

func (m *TxInputType) GetMultisig() types.MultisigRedeemScriptTyper {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxInputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

// *
// Structure representing transaction output
// @used_in SimpleSignTx
// @used_in TransactionType
type TxOutputType struct {
	Address          *string                   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	AddressN         []uint32                  `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Amount           *uint64                   `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	ScriptType       *OutputScriptType         `protobuf:"varint,4,req,name=script_type,json=scriptType,enum=OutputScriptType" json:"script_type,omitempty"`
	Multisig         *MultisigRedeemScriptType `protobuf:"bytes,5,opt,name=multisig" json:"multisig,omitempty"`
	OpReturnData     []byte                    `protobuf:"bytes,6,opt,name=op_return_data,json=opReturnData" json:"op_return_data,omitempty"`
	AddressType      *OutputAddressType        `protobuf:"varint,7,opt,name=address_type,json=addressType,enum=OutputAddressType" json:"address_type,omitempty"`
	ExchangeType     *ExchangeType             `protobuf:"bytes,8,opt,name=exchange_type,json=exchangeType" json:"exchange_type,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *TxOutputType) Reset()                    { *m = TxOutputType{} }
func (m *TxOutputType) String() string            { return proto.CompactTextString(m) }
func (*TxOutputType) ProtoMessage()               {}
func (*TxOutputType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TxOutputType) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *TxOutputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxOutputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputType) GetScriptType() types.OutputScriptTyper {
	if m != nil && m.ScriptType != nil {
		return m.ScriptType
	}
	x := OutputScriptType(OutputScriptType_PAYTOADDRESS)
	return &x
}

func (m *TxOutputType) GetMultisig() types.MultisigRedeemScriptTyper {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxOutputType) GetOpReturnData() []byte {
	if m != nil {
		return m.OpReturnData
	}
	return nil
}

func (m *TxOutputType) GetAddressType() types.OutputAddressTyper {
	if m != nil && m.AddressType != nil {
		return m.AddressType
	}
	x := OutputAddressType(OutputAddressType_SPEND)
	return &x
}

func (m *TxOutputType) GetExchangeType() types.ExchangeTyper {
	if m != nil {
		return m.ExchangeType
	}
	return nil
}

// *
// Structure representing compiled transaction output
// @used_in TransactionType
type TxOutputBinType struct {
	Amount           *uint64 `protobuf:"varint,1,req,name=amount" json:"amount,omitempty"`
	ScriptPubkey     []byte  `protobuf:"bytes,2,req,name=script_pubkey,json=scriptPubkey" json:"script_pubkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxOutputBinType) Reset()                    { *m = TxOutputBinType{} }
func (m *TxOutputBinType) String() string            { return proto.CompactTextString(m) }
func (*TxOutputBinType) ProtoMessage()               {}
func (*TxOutputBinType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TxOutputBinType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputBinType) GetScriptPubkey() []byte {
	if m != nil {
		return m.ScriptPubkey
	}
	return nil
}

// *
// Structure representing transaction
// @used_in SimpleSignTx,
type TransactionType struct {
	Version          *uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Inputs           []*TxInputType     `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
	BinOutputs       []*TxOutputBinType `protobuf:"bytes,3,rep,name=bin_outputs,json=binOutputs" json:"bin_outputs,omitempty"`
	Outputs          []*TxOutputType    `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	LockTime         *uint32            `protobuf:"varint,4,opt,name=lock_time,json=lockTime" json:"lock_time,omitempty"`
	InputsCnt        *uint32            `protobuf:"varint,6,opt,name=inputs_cnt,json=inputsCnt" json:"inputs_cnt,omitempty"`
	OutputsCnt       *uint32            `protobuf:"varint,7,opt,name=outputs_cnt,json=outputsCnt" json:"outputs_cnt,omitempty"`
	ExtraData        []byte             `protobuf:"bytes,8,opt,name=extra_data,json=extraData" json:"extra_data,omitempty"`
	ExtraDataLen     *uint32            `protobuf:"varint,9,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *TransactionType) Reset()                    { *m = TransactionType{} }
func (m *TransactionType) String() string            { return proto.CompactTextString(m) }
func (*TransactionType) ProtoMessage()               {}
func (*TransactionType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TransactionType) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *TransactionType) GetInputs() []types.TxInputTyper {
	if m != nil {
		l := len(m.Inputs)
		z := make([]types.TxInputTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.Inputs[i]
		}
		return z
	}
	return nil
}

func (m *TransactionType) GetBinOutputs() []types.TxOutputBinTyper {
	if m != nil {
		l := len(m.BinOutputs)
		z := make([]types.TxOutputBinTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.BinOutputs[i]
		}
		return z

	}
	return nil
}

func (m *TransactionType) GetOutputs() []types.TxOutputTyper {
	if m != nil {
		l := len(m.Outputs)
		z := make([]types.TxOutputTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.Outputs[i]
		}
		return z
	}
	return nil
}

func (m *TransactionType) GetLockTime() uint32 {
	if m != nil && m.LockTime != nil {
		return *m.LockTime
	}
	return 0
}

func (m *TransactionType) GetInputsCnt() uint32 {
	if m != nil && m.InputsCnt != nil {
		return *m.InputsCnt
	}
	return 0
}

func (m *TransactionType) GetOutputsCnt() uint32 {
	if m != nil && m.OutputsCnt != nil {
		return *m.OutputsCnt
	}
	return 0
}

func (m *TransactionType) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *TransactionType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

// *
// Structure representing raw transaction
// @used_in RawTxAck
type RawTransactionType struct {
	Payload          []byte `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RawTransactionType) Reset()                    { *m = RawTransactionType{} }
func (m *RawTransactionType) String() string            { return proto.CompactTextString(m) }
func (*RawTransactionType) ProtoMessage()               {}
func (*RawTransactionType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RawTransactionType) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// *
// Structure representing request details
// @used_in TxRequest
type TxRequestDetailsType struct {
	RequestIndex     *uint32 `protobuf:"varint,1,opt,name=request_index,json=requestIndex" json:"request_index,omitempty"`
	TxHash           []byte  `protobuf:"bytes,2,opt,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	ExtraDataLen     *uint32 `protobuf:"varint,3,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	ExtraDataOffset  *uint32 `protobuf:"varint,4,opt,name=extra_data_offset,json=extraDataOffset" json:"extra_data_offset,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxRequestDetailsType) Reset()                    { *m = TxRequestDetailsType{} }
func (m *TxRequestDetailsType) String() string            { return proto.CompactTextString(m) }
func (*TxRequestDetailsType) ProtoMessage()               {}
func (*TxRequestDetailsType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TxRequestDetailsType) GetRequestIndex() uint32 {
	if m != nil && m.RequestIndex != nil {
		return *m.RequestIndex
	}
	return 0
}

func (m *TxRequestDetailsType) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TxRequestDetailsType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

func (m *TxRequestDetailsType) GetExtraDataOffset() uint32 {
	if m != nil && m.ExtraDataOffset != nil {
		return *m.ExtraDataOffset
	}
	return 0
}

// *
// Structure representing serialized data
// @used_in TxRequest
type TxRequestSerializedType struct {
	SignatureIndex   *uint32 `protobuf:"varint,1,opt,name=signature_index,json=signatureIndex" json:"signature_index,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	SerializedTx     []byte  `protobuf:"bytes,3,opt,name=serialized_tx,json=serializedTx" json:"serialized_tx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxRequestSerializedType) Reset()                    { *m = TxRequestSerializedType{} }
func (m *TxRequestSerializedType) String() string            { return proto.CompactTextString(m) }
func (*TxRequestSerializedType) ProtoMessage()               {}
func (*TxRequestSerializedType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TxRequestSerializedType) GetSignatureIndex() uint32 {
	if m != nil && m.SignatureIndex != nil {
		return *m.SignatureIndex
	}
	return 0
}

func (m *TxRequestSerializedType) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TxRequestSerializedType) GetSerializedTx() []byte {
	if m != nil {
		return m.SerializedTx
	}
	return nil
}

// *
// Structure representing identity data
// @used_in IdentityType
type IdentityType struct {
	Proto            *string `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	User             *string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Host             *string `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port             *string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	Path             *string `protobuf:"bytes,5,opt,name=path" json:"path,omitempty"`
	Index            *uint32 `protobuf:"varint,6,opt,name=index,def=0" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IdentityType) Reset()                    { *m = IdentityType{} }
func (m *IdentityType) String() string            { return proto.CompactTextString(m) }
func (*IdentityType) ProtoMessage()               {}
func (*IdentityType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

const Default_IdentityType_Index uint32 = 0

func (m *IdentityType) GetProto() string {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return ""
}

func (m *IdentityType) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *IdentityType) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *IdentityType) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *IdentityType) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *IdentityType) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_IdentityType_Index
}

// *
// Structure representing policy data
// @used_in ApplyPolicy
type PolicyType struct {
	PolicyName       *string `protobuf:"bytes,1,opt,name=policy_name,json=policyName" json:"policy_name,omitempty"`
	Enabled          *bool   `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PolicyType) Reset()                    { *m = PolicyType{} }
func (m *PolicyType) String() string            { return proto.CompactTextString(m) }
func (*PolicyType) ProtoMessage()               {}
func (*PolicyType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PolicyType) GetPolicyName() string {
	if m != nil && m.PolicyName != nil {
		return *m.PolicyName
	}
	return ""
}

func (m *PolicyType) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

// *
// Structure representing exchange data
// @used_in TxOutputType
type ExchangeType struct {
	SignedExchangeResponse *exchange.SignedExchangeResponse `protobuf:"bytes,1,opt,name=signed_exchange_response,json=signedExchangeResponse" json:"signed_exchange_response,omitempty"`
	WithdrawalCoinName     *string                          `protobuf:"bytes,2,opt,name=withdrawal_coin_name,json=withdrawalCoinName,def=Bitcoin" json:"withdrawal_coin_name,omitempty"`
	WithdrawalAddressN     []uint32                         `protobuf:"varint,3,rep,name=withdrawal_address_n,json=withdrawalAddressN" json:"withdrawal_address_n,omitempty"`
	ReturnAddressN         []uint32                         `protobuf:"varint,4,rep,name=return_address_n,json=returnAddressN" json:"return_address_n,omitempty"`
	XXX_unrecognized       []byte                           `json:"-"`
}

func (m *ExchangeType) Reset()                    { *m = ExchangeType{} }
func (m *ExchangeType) String() string            { return proto.CompactTextString(m) }
func (*ExchangeType) ProtoMessage()               {}
func (*ExchangeType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

const Default_ExchangeType_WithdrawalCoinName string = "Bitcoin"

func (m *ExchangeType) GetSignedExchangeResponse() *exchange.SignedExchangeResponse {
	if m != nil {
		return m.SignedExchangeResponse
	}
	return nil
}

func (m *ExchangeType) GetWithdrawalCoinName() string {
	if m != nil && m.WithdrawalCoinName != nil {
		return *m.WithdrawalCoinName
	}
	return Default_ExchangeType_WithdrawalCoinName
}

func (m *ExchangeType) GetWithdrawalAddressN() []uint32 {
	if m != nil {
		return m.WithdrawalAddressN
	}
	return nil
}

func (m *ExchangeType) GetReturnAddressN() []uint32 {
	if m != nil {
		return m.ReturnAddressN
	}
	return nil
}

var E_WireIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "wire_in",
	Tag:           "varint,50002,opt,name=wire_in,json=wireIn",
	Filename:      "types.proto",
}

var E_WireOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "wire_out",
	Tag:           "varint,50003,opt,name=wire_out,json=wireOut",
	Filename:      "types.proto",
}

var E_WireDebugIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50004,
	Name:          "wire_debug_in",
	Tag:           "varint,50004,opt,name=wire_debug_in,json=wireDebugIn",
	Filename:      "types.proto",
}

var E_WireDebugOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50005,
	Name:          "wire_debug_out",
	Tag:           "varint,50005,opt,name=wire_debug_out,json=wireDebugOut",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*HDNodeType)(nil), "keepkeyHDNodeType")
	proto.RegisterType((*HDNodePathType)(nil), "keepkeyHDNodePathType")
	proto.RegisterType((*CoinType)(nil), "keepkeyCoinType")
	proto.RegisterType((*MultisigRedeemScriptType)(nil), "keepkeyMultisigRedeemScriptType")
	proto.RegisterType((*TxInputType)(nil), "keepkeyTxInputType")
	proto.RegisterType((*TxOutputType)(nil), "keepkeyTxOutputType")
	proto.RegisterType((*TxOutputBinType)(nil), "keepkeyTxOutputBinType")
	proto.RegisterType((*TransactionType)(nil), "keepkeyTransactionType")
	proto.RegisterType((*RawTransactionType)(nil), "keepkeyRawTransactionType")
	proto.RegisterType((*TxRequestDetailsType)(nil), "keepkeyTxRequestDetailsType")
	proto.RegisterType((*TxRequestSerializedType)(nil), "keepkeyTxRequestSerializedType")
	proto.RegisterType((*IdentityType)(nil), "keepkeyIdentityType")
	proto.RegisterType((*PolicyType)(nil), "keepkeyPolicyType")
	proto.RegisterType((*ExchangeType)(nil), "keepkeyExchangeType")
	proto.RegisterEnum("keepkeyFailureType", FailureType_name, FailureType_value)
	proto.RegisterEnum("keepkeyOutputScriptType", OutputScriptType_name, OutputScriptType_value)
	proto.RegisterEnum("keepkeyInputScriptType", InputScriptType_name, InputScriptType_value)
	proto.RegisterEnum("keepkeyRequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("keepkeyOutputAddressType", OutputAddressType_name, OutputAddressType_value)
	proto.RegisterEnum("keepkeyButtonRequestType", ButtonRequestType_name, ButtonRequestType_value)
	proto.RegisterEnum("keepkeyPinMatrixRequestType", PinMatrixRequestType_name, PinMatrixRequestType_value)
	/*proto.RegisterExtension(E_WireIn)
	proto.RegisterExtension(E_WireOut)
	proto.RegisterExtension(E_WireDebugIn)
	proto.RegisterExtension(E_WireDebugOut)*/
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xdd, 0x72, 0xdb, 0xb8,
	0xf5, 0x5f, 0x4a, 0xb2, 0x25, 0x1d, 0x49, 0x36, 0x0c, 0x7b, 0x63, 0x25, 0x71, 0x12, 0xaf, 0x92,
	0xd9, 0x78, 0xfd, 0xff, 0x57, 0x9b, 0xd5, 0x24, 0xdb, 0x89, 0xa7, 0xd3, 0x8e, 0x62, 0xcb, 0xb1,
	0x26, 0x89, 0xac, 0x42, 0x74, 0xe3, 0x5e, 0x69, 0x68, 0x12, 0x16, 0x31, 0xa6, 0x40, 0x96, 0x04,
	0x6d, 0xa9, 0x37, 0xbd, 0xda, 0xf6, 0xaa, 0xaf, 0xd1, 0xb7, 0xe8, 0x4c, 0x5f, 0xa0, 0xd3, 0x99,
	0x7e, 0x5c, 0xf4, 0x1d, 0xfa, 0x00, 0xbd, 0xec, 0x00, 0x04, 0x25, 0xca, 0x72, 0xda, 0xdc, 0x09,
	0xbf, 0xdf, 0x39, 0x07, 0x07, 0xe7, 0x0b, 0xa0, 0xa0, 0x22, 0xa6, 0x01, 0x8d, 0x9a, 0x41, 0xe8,
	0x0b, 0xff, 0xc1, 0xee, 0xc8, 0xf7, 0x47, 0x1e, 0xfd, 0x56, 0xad, 0x2e, 0xe2, 0xcb, 0x6f, 0x1d,
	0x1a, 0xd9, 0x21, 0x0b, 0x84, 0x1f, 0x6a, 0x89, 0x35, 0x3a, 0xb1, 0x5d, 0x8b, 0x8f, 0x68, 0xb2,
	0x6e, 0xfc, 0xc9, 0x00, 0x38, 0x39, 0xea, 0xf9, 0x0e, 0x35, 0xa7, 0x01, 0xc5, 0x5b, 0xb0, 0xe2,
	0xd0, 0x40, 0xb8, 0x75, 0x63, 0x37, 0xb7, 0x57, 0x23, 0xc9, 0x02, 0xef, 0x42, 0xe5, 0x92, 0xf1,
	0x11, 0x0d, 0x83, 0x90, 0x71, 0x51, 0xcf, 0x29, 0x2e, 0x0b, 0xe1, 0x87, 0x50, 0xb6, 0x5d, 0xe6,
	0x39, 0x43, 0x1e, 0x8f, 0xeb, 0x79, 0xc5, 0x97, 0x14, 0xd0, 0x8b, 0xc7, 0xf8, 0x11, 0x80, 0xed,
	0x5a, 0x8c, 0x0f, 0x6d, 0xdf, 0xa1, 0xf5, 0xc2, 0x6e, 0x6e, 0xaf, 0x4a, 0xca, 0x0a, 0x39, 0xf4,
	0x1d, 0x8a, 0x9f, 0x40, 0x25, 0x08, 0xd9, 0xb5, 0x25, 0xe8, 0xf0, 0x8a, 0x4e, 0xeb, 0x2b, 0xbb,
	0xc6, 0x5e, 0x95, 0x80, 0x86, 0xde, 0xd1, 0xa9, 0xd4, 0x0f, 0xe2, 0x0b, 0x8f, 0xd9, 0x8a, 0x5f,
	0x55, 0x7c, 0x39, 0x41, 0xde, 0xd1, 0x69, 0xa3, 0x07, 0x6b, 0xc9, 0x09, 0xfa, 0x96, 0x70, 0xd5,
	0x29, 0x9e, 0x40, 0x81, 0xcb, 0xad, 0xe4, 0x21, 0x2a, 0xad, 0x4a, 0x73, 0x7e, 0x40, 0xa2, 0x08,
	0xe9, 0xae, 0xe5, 0x38, 0x21, 0x8d, 0xa2, 0x21, 0xaf, 0xe7, 0x76, 0xf3, 0xd2, 0x5d, 0x0d, 0xf4,
	0x1a, 0x3f, 0xe4, 0xa1, 0x74, 0xe8, 0x33, 0xae, 0x4c, 0xc9, 0x83, 0xf9, 0x8c, 0x0f, 0xb9, 0x35,
	0x96, 0xf6, 0x8c, 0xbd, 0x32, 0x29, 0x49, 0xa0, 0x67, 0x8d, 0x29, 0x7e, 0x0a, 0x35, 0x45, 0x46,
	0xae, 0x1f, 0x0a, 0x3b, 0x96, 0x91, 0x91, 0x02, 0x55, 0x09, 0x0e, 0x34, 0x86, 0x9f, 0x41, 0x35,
	0xdd, 0x4b, 0xa6, 0xaa, 0x9e, 0xdf, 0x35, 0xf6, 0x6a, 0x07, 0xc6, 0x0b, 0x52, 0xd1, 0x70, 0xba,
	0xcf, 0xd8, 0x9a, 0x5c, 0x52, 0x3a, 0xbc, 0xba, 0xa8, 0x17, 0x76, 0x8d, 0xbd, 0x02, 0x29, 0x25,
	0xc0, 0xbb, 0x0b, 0xfc, 0x23, 0xd8, 0xc8, 0x9a, 0x18, 0x06, 0xad, 0xc8, 0x55, 0x71, 0xaa, 0x1d,
	0x18, 0xaf, 0xc8, 0x7a, 0xc6, 0x4e, 0xbf, 0x15, 0xb9, 0xf8, 0x3b, 0xd8, 0xbc, 0x25, 0x7e, 0x13,
	0x5c, 0xb9, 0x2a, 0x70, 0xb5, 0x03, 0xe3, 0x7b, 0xb2, 0xb1, 0xa0, 0x20, 0x39, 0xfc, 0x02, 0xf0,
	0x6d, 0x95, 0xc8, 0xad, 0x17, 0x95, 0x46, 0xee, 0xbb, 0x17, 0x04, 0x2d, 0xaa, 0x44, 0x2e, 0x6e,
	0xc1, 0x97, 0x11, 0x1b, 0x71, 0xea, 0x0c, 0xc7, 0x34, 0x8a, 0xac, 0x11, 0x1d, 0xba, 0xd4, 0x72,
	0x68, 0x58, 0x2f, 0xa9, 0x18, 0x6c, 0x26, 0xe4, 0x87, 0x84, 0x3b, 0x51, 0x14, 0xfe, 0x7f, 0xc0,
	0x17, 0x2c, 0x78, 0xf9, 0x72, 0x68, 0xd9, 0xb6, 0x1f, 0x73, 0x31, 0x0c, 0x2c, 0xe1, 0xd6, 0xcb,
	0x72, 0x17, 0x82, 0x14, 0xd3, 0x4e, 0x08, 0x99, 0xc9, 0x46, 0x04, 0xf5, 0x0f, 0xb1, 0x27, 0x58,
	0xc4, 0x46, 0x84, 0x3a, 0x94, 0x8e, 0x07, 0xaa, 0x94, 0x55, 0xb8, 0xbe, 0x81, 0x62, 0x10, 0x5f,
	0x5c, 0xd1, 0x69, 0x54, 0x37, 0x76, 0xf3, 0x7b, 0x95, 0xd6, 0x7a, 0x73, 0xb1, 0x06, 0x48, 0xca,
	0xe3, 0xc7, 0x00, 0xd2, 0x17, 0x4b, 0xc4, 0x21, 0x8d, 0x54, 0xb2, 0xab, 0x24, 0x83, 0xe0, 0x2a,
	0x18, 0xe3, 0x24, 0x29, 0xc4, 0x18, 0x37, 0xfe, 0x98, 0x83, 0x8a, 0x39, 0xe9, 0xf2, 0x20, 0x16,
	0x69, 0x5e, 0xe6, 0x95, 0x62, 0x2c, 0x56, 0x8a, 0x24, 0x83, 0x90, 0x5e, 0x0f, 0x5d, 0x2b, 0x72,
	0x55, 0x57, 0x54, 0x49, 0x49, 0x02, 0x27, 0x56, 0xe4, 0xaa, 0xaa, 0x95, 0x24, 0xe3, 0x0e, 0x9d,
	0xe8, 0x9e, 0x50, 0xe2, 0x5d, 0x09, 0x48, 0x3a, 0x69, 0xcd, 0x61, 0xc4, 0x46, 0x2a, 0xe3, 0x55,
	0x52, 0x4e, 0x90, 0x01, 0x1b, 0xe1, 0xaf, 0xa1, 0x14, 0xd1, 0x5f, 0xc5, 0x94, 0xdb, 0x54, 0x67,
	0x1a, 0x5e, 0xb6, 0x5e, 0xbf, 0x7c, 0xfd, 0xfd, 0x8f, 0x5b, 0xaf, 0x5f, 0x91, 0x19, 0x87, 0x7f,
	0x06, 0x15, 0x6d, 0x46, 0x15, 0x97, 0xcc, 0xf1, 0x5a, 0x0b, 0x35, 0xd5, 0x01, 0xe6, 0xf1, 0x3a,
	0xa8, 0x0e, 0xfa, 0x9d, 0xde, 0x51, 0xfb, 0xe8, 0x88, 0x74, 0x06, 0x03, 0xa2, 0x77, 0x56, 0x07,
	0x7c, 0x05, 0xa5, 0xb1, 0x8e, 0xb2, 0xca, 0x77, 0xa5, 0x75, 0xbf, 0xf9, 0xa9, 0xb0, 0x93, 0x99,
	0x28, 0xbe, 0x07, 0xab, 0xd6, 0x58, 0xa6, 0x4a, 0xe5, 0xbb, 0x40, 0xf4, 0xaa, 0xf1, 0xcf, 0x1c,
	0x54, 0xcd, 0xc9, 0x69, 0x2c, 0xd2, 0x00, 0xd6, 0xa1, 0xa8, 0xe3, 0xa5, 0xdb, 0x27, 0x5d, 0xfe,
	0xd7, 0x26, 0xcc, 0xd8, 0x97, 0x91, 0x9b, 0xd9, 0xc7, 0xad, 0xc5, 0xf3, 0xca, 0x61, 0xb2, 0xd6,
	0xda, 0x68, 0x26, 0x1b, 0x66, 0x3c, 0xfd, 0xd4, 0x11, 0x57, 0x3e, 0xff, 0x88, 0xcf, 0x60, 0xcd,
	0x0f, 0x86, 0x21, 0x15, 0x71, 0xc8, 0x87, 0x8e, 0x25, 0x2c, 0x3d, 0x7a, 0xaa, 0x7e, 0x40, 0x14,
	0x78, 0x64, 0x09, 0x0b, 0xbf, 0xba, 0xd5, 0xde, 0x45, 0x95, 0x01, 0xac, 0x3d, 0x6a, 0xcf, 0xdb,
	0x66, 0xb1, 0xdf, 0x5b, 0x50, 0x4b, 0x27, 0x71, 0xa2, 0x57, 0x52, 0x8e, 0xd5, 0x9a, 0x1d, 0x8d,
	0x2a, 0x95, 0x2a, 0xcd, 0xac, 0x1a, 0x3d, 0x58, 0x4f, 0x43, 0xfb, 0x46, 0x8f, 0xa7, 0x79, 0x98,
	0x8c, 0x85, 0x30, 0x3d, 0x85, 0x9a, 0x0e, 0x53, 0xd2, 0x06, 0xba, 0x3a, 0xab, 0x09, 0xd8, 0x57,
	0x58, 0xe3, 0x2f, 0x39, 0x58, 0x37, 0x43, 0x8b, 0x47, 0x96, 0x2d, 0x98, 0xcf, 0xd3, 0x74, 0x5d,
	0xd3, 0x30, 0x62, 0x3e, 0x57, 0xe9, 0xaa, 0x91, 0x74, 0x89, 0x9f, 0xc1, 0x2a, 0x93, 0x55, 0x95,
	0xf4, 0x50, 0xa5, 0x55, 0x6d, 0x66, 0xfa, 0x84, 0x68, 0x0e, 0x7f, 0x07, 0x95, 0x0b, 0xc6, 0x87,
	0xbe, 0xf2, 0x32, 0xaa, 0xe7, 0x95, 0x28, 0x6a, 0xde, 0xf2, 0x9b, 0xc0, 0x05, 0xe3, 0x09, 0x12,
	0xe1, 0xe7, 0x50, 0x4c, 0xc5, 0x57, 0x94, 0x78, 0xad, 0x99, 0xad, 0x20, 0x92, 0xb2, 0xb2, 0x60,
	0x3c, 0xdf, 0xbe, 0x1a, 0x0a, 0x36, 0xa6, 0xaa, 0x63, 0x6a, 0xa4, 0x24, 0x01, 0x93, 0x8d, 0xa9,
	0xec, 0xa7, 0xc4, 0x85, 0xa1, 0xcd, 0x45, 0x32, 0xeb, 0x48, 0x39, 0x41, 0x0e, 0xb9, 0x90, 0x97,
	0x8c, 0x36, 0xa3, 0x78, 0x35, 0xd9, 0x08, 0x68, 0x48, 0x0a, 0x3c, 0x02, 0xa0, 0x13, 0x11, 0x5a,
	0x49, 0xa6, 0x4b, 0x49, 0x3f, 0x2a, 0x44, 0xa5, 0xf9, 0x19, 0xac, 0xcd, 0xe9, 0xa1, 0x47, 0xb9,
	0x1e, 0x5b, 0xd5, 0x99, 0xc8, 0x7b, 0xca, 0x1b, 0x4d, 0xc0, 0xc4, 0xba, 0xb9, 0x23, 0xa6, 0x81,
	0x35, 0xf5, 0x7c, 0xcb, 0x51, 0x59, 0xaa, 0x92, 0x74, 0xd9, 0xf8, 0x83, 0x01, 0x5b, 0xe6, 0x84,
	0xc8, 0x66, 0x8e, 0xc4, 0x11, 0x15, 0x16, 0xf3, 0x92, 0xf2, 0x78, 0x0a, 0xb5, 0x30, 0x41, 0xf5,
	0xfc, 0x48, 0x92, 0x51, 0xd5, 0x60, 0x32, 0x42, 0xb6, 0xa1, 0x28, 0x26, 0xe9, 0xf0, 0x91, 0xfe,
	0xae, 0x8a, 0x89, 0x1a, 0x3d, 0xcb, 0xce, 0xe6, 0x97, 0x9d, 0xc5, 0xfb, 0xb0, 0x91, 0x91, 0xf2,
	0x2f, 0x2f, 0x23, 0x2a, 0x74, 0x58, 0xd7, 0x67, 0x82, 0xa7, 0x0a, 0x6e, 0xfc, 0x60, 0xc0, 0xf6,
	0xcc, 0xd1, 0x01, 0x0d, 0x99, 0xe5, 0xb1, 0x5f, 0x53, 0x47, 0xf9, 0xfa, 0x1c, 0xd6, 0x67, 0xe3,
	0x74, 0xc1, 0xdb, 0xb5, 0x19, 0x9c, 0xf8, 0xbb, 0x03, 0xe5, 0x19, 0xa2, 0x3d, 0x9e, 0x03, 0xaa,
	0x64, 0x67, 0x86, 0x87, 0x62, 0xa2, 0x7c, 0x96, 0x25, 0x3b, 0xdf, 0x6d, 0xd2, 0xf8, 0xbd, 0x01,
	0xd5, 0xae, 0x43, 0xb9, 0x60, 0x62, 0x9a, 0x3e, 0x58, 0xd4, 0x43, 0x46, 0x0f, 0x97, 0x64, 0x81,
	0x31, 0x14, 0xe2, 0x88, 0x86, 0xfa, 0x3e, 0x56, 0xbf, 0x25, 0xe6, 0xfa, 0x91, 0x50, 0x66, 0xcb,
	0x44, 0xfd, 0x96, 0x58, 0xe0, 0x87, 0xc9, 0xa9, 0xcb, 0x44, 0xfd, 0x56, 0x98, 0xbc, 0x96, 0x56,
	0x34, 0x66, 0x09, 0x17, 0x6f, 0xc3, 0x4a, 0x72, 0xb0, 0xd5, 0xf4, 0xf2, 0x4e, 0xd6, 0x8d, 0xb7,
	0x00, 0x7d, 0xdf, 0x63, 0xf6, 0x54, 0xbf, 0x3b, 0x2a, 0x81, 0x5a, 0x65, 0x9f, 0x0b, 0x90, 0x40,
	0xea, 0xc1, 0x50, 0x87, 0x22, 0xe5, 0xd6, 0x85, 0x47, 0x1d, 0xe5, 0x5a, 0x89, 0xa4, 0xcb, 0xc6,
	0xbf, 0x0d, 0xa8, 0x66, 0x5b, 0x1f, 0xff, 0x1c, 0xea, 0xfa, 0x7e, 0x9d, 0xcd, 0x89, 0x90, 0x46,
	0x81, 0xcf, 0xa3, 0xc4, 0x70, 0xa5, 0xb5, 0xdd, 0x1c, 0x28, 0x81, 0x54, 0x8d, 0x68, 0x9a, 0xdc,
	0x8b, 0xee, 0xc4, 0xf1, 0x6b, 0xd8, 0xba, 0x61, 0xc2, 0x75, 0x42, 0xeb, 0xc6, 0xf2, 0x86, 0xf3,
	0x67, 0x8d, 0x8a, 0xd2, 0x41, 0xf1, 0x0d, 0x13, 0x12, 0x23, 0x78, 0x2e, 0x74, 0x98, 0xbe, 0x74,
	0x5e, 0x2c, 0xa8, 0xce, 0xc7, 0x76, 0x5e, 0x8d, 0xed, 0x8c, 0x46, 0x3b, 0x1d, 0xe0, 0x7b, 0x80,
	0xf4, 0xe8, 0x9c, 0x4b, 0x17, 0x94, 0xf4, 0x5a, 0x82, 0xa7, 0x92, 0xfb, 0x7f, 0xce, 0x41, 0xe5,
	0xd8, 0x62, 0x5e, 0x1c, 0x26, 0x27, 0x7f, 0x04, 0xf7, 0xf5, 0x72, 0x78, 0xc6, 0xe9, 0x24, 0xa0,
	0xb6, 0x98, 0x3d, 0x24, 0x90, 0x81, 0x1f, 0xc0, 0xbd, 0x94, 0x7e, 0x13, 0x0b, 0xe1, 0xf3, 0x8e,
	0x16, 0x41, 0x39, 0xbc, 0x0d, 0x9b, 0x29, 0x37, 0x98, 0x72, 0x61, 0x4d, 0x3a, 0x61, 0xe8, 0x87,
	0x28, 0x8f, 0x1f, 0xc2, 0x76, 0x4a, 0xb4, 0x55, 0x63, 0x1e, 0x5a, 0xdc, 0xa6, 0x9e, 0x47, 0x1d,
	0x54, 0xc8, 0x6a, 0xf5, 0xd9, 0xdc, 0xdc, 0x0a, 0xae, 0xc3, 0x56, 0x86, 0x98, 0xab, 0xac, 0xe2,
	0x7b, 0x80, 0x33, 0x4c, 0x97, 0x5f, 0x5b, 0x1e, 0x73, 0x50, 0x11, 0xef, 0x40, 0x3d, 0xc5, 0x35,
	0x38, 0x48, 0x0b, 0x1c, 0x95, 0xf0, 0x06, 0xd4, 0x52, 0xf6, 0x54, 0xb8, 0x34, 0x44, 0xe5, 0xec,
	0x69, 0x7a, 0xbe, 0xe8, 0x70, 0x3f, 0x1e, 0xb9, 0xc7, 0x31, 0x77, 0x22, 0x04, 0xb7, 0xb8, 0x2e,
	0x67, 0x42, 0x37, 0x02, 0xaa, 0xe0, 0xfb, 0xf0, 0x65, 0xca, 0x1d, 0xb3, 0x70, 0x7c, 0x63, 0x85,
	0x34, 0x39, 0xab, 0xbd, 0xff, 0x3b, 0x03, 0xd0, 0xed, 0xfb, 0x10, 0x23, 0xa8, 0xf6, 0xdb, 0xbf,
	0x34, 0x4f, 0xf5, 0x13, 0x00, 0x7d, 0x81, 0x37, 0x61, 0x5d, 0x21, 0x83, 0x43, 0xd2, 0xed, 0x9b,
	0x27, 0xed, 0xc1, 0x09, 0x32, 0xa4, 0x87, 0x0a, 0xfc, 0x70, 0xf6, 0xde, 0xec, 0x0e, 0xba, 0x6f,
	0x51, 0x6e, 0x06, 0x9d, 0xf6, 0x49, 0xc7, 0x3c, 0x23, 0x3d, 0x94, 0x9f, 0x19, 0xfb, 0xd8, 0x35,
	0x7b, 0xd2, 0x58, 0x01, 0x6f, 0x01, 0x52, 0x48, 0xbf, 0x35, 0x38, 0x49, 0xd1, 0x95, 0x7d, 0x0f,
	0xd6, 0x6f, 0x3d, 0x44, 0xa4, 0x6a, 0xf6, 0x29, 0x82, 0xbe, 0x90, 0xf6, 0x15, 0x32, 0xdb, 0xd2,
	0xc0, 0x55, 0x28, 0x75, 0xce, 0xcd, 0x0e, 0xe9, 0xb5, 0xdf, 0xa3, 0xdc, 0x4c, 0x25, 0xb5, 0x9b,
	0x97, 0xbb, 0x29, 0x24, 0xbb, 0x5b, 0x61, 0xff, 0x0c, 0x2a, 0x7a, 0x40, 0xa9, 0x9d, 0x2a, 0x50,
	0x34, 0xcf, 0xbb, 0xbd, 0xfe, 0x99, 0x89, 0xbe, 0x90, 0x16, 0xcd, 0xf3, 0xd3, 0x33, 0x53, 0xae,
	0x0c, 0x0c, 0xb0, 0x6a, 0x9e, 0x7f, 0xe8, 0x98, 0x6d, 0x94, 0xc3, 0x6b, 0x00, 0xe6, 0xf9, 0x71,
	0xb7, 0xd7, 0x1d, 0x9c, 0x74, 0x8e, 0x50, 0x1e, 0xaf, 0x43, 0xc5, 0x3c, 0xef, 0x9c, 0x9b, 0xa4,
	0x7d, 0xd4, 0x36, 0xdb, 0xa8, 0xb0, 0x7f, 0x0c, 0x1b, 0x4b, 0x77, 0x39, 0x2e, 0xc3, 0x8a, 0xf2,
	0x40, 0x9b, 0x26, 0xed, 0xde, 0xe0, 0xb8, 0x43, 0x12, 0xd3, 0x87, 0x27, 0xed, 0xde, 0xdb, 0x0e,
	0xca, 0x25, 0xc7, 0xd0, 0xab, 0xfc, 0xfe, 0xbf, 0x8a, 0xb0, 0x91, 0x14, 0x6c, 0xd6, 0xcb, 0x6d,
	0xd8, 0x5c, 0x00, 0x75, 0x61, 0x18, 0xb8, 0x01, 0x8f, 0x17, 0x89, 0x63, 0x4a, 0x4f, 0xaf, 0x69,
	0x68, 0xba, 0x21, 0x8d, 0x5c, 0xdf, 0x93, 0xe5, 0xfe, 0x04, 0x1e, 0x2e, 0xca, 0x1c, 0xfa, 0xfc,
	0x92, 0x85, 0xe3, 0xc4, 0x5f, 0x94, 0x97, 0xad, 0xb4, 0x28, 0x40, 0x68, 0x44, 0xc5, 0x11, 0xbd,
	0x66, 0x36, 0x45, 0x85, 0x65, 0x5a, 0xeb, 0x7f, 0xf4, 0x43, 0x59, 0xfe, 0x3b, 0x50, 0x5f, 0xa4,
	0x3f, 0xb2, 0x80, 0x6a, 0xe5, 0xd5, 0x65, 0xe5, 0x7e, 0xe8, 0x0b, 0x6a, 0x8b, 0x43, 0xcb, 0xf3,
	0x50, 0x51, 0xf6, 0xce, 0x22, 0x2d, 0x1b, 0xc1, 0x9c, 0xa0, 0xd2, 0xb2, 0xd7, 0x69, 0x01, 0x1f,
	0xba, 0xd4, 0xbe, 0x42, 0x65, 0x59, 0xdb, 0x8b, 0x02, 0x3a, 0xf2, 0x08, 0x3e, 0xad, 0xdb, 0x09,
	0xad, 0x88, 0xa2, 0x0a, 0xde, 0x87, 0xaf, 0xef, 0x3c, 0x92, 0xba, 0x93, 0x2f, 0x69, 0x68, 0xfa,
	0xfa, 0x13, 0x03, 0x55, 0xf1, 0xff, 0xc1, 0xf3, 0xff, 0x21, 0x9b, 0x7e, 0x51, 0xa0, 0xda, 0x1d,
	0xb1, 0x52, 0xc3, 0xf5, 0xbd, 0x75, 0x41, 0x3d, 0xb4, 0x86, 0x77, 0x61, 0xe7, 0x6e, 0x9a, 0x8f,
	0x62, 0x39, 0xb7, 0xd6, 0x97, 0x13, 0xda, 0x51, 0xa3, 0xbf, 0x6f, 0x45, 0x51, 0xe0, 0x2a, 0xef,
	0x11, 0x7e, 0x0a, 0x4f, 0x16, 0x65, 0x8e, 0x58, 0x74, 0x4b, 0x68, 0x03, 0x3f, 0x87, 0xa7, 0xb7,
	0x0d, 0xd9, 0xe1, 0x34, 0x10, 0x6d, 0xae, 0x86, 0x4d, 0x3a, 0x29, 0xf1, 0xb2, 0x4f, 0x5a, 0x30,
	0x95, 0xd8, 0x5c, 0xf6, 0xa9, 0x3b, 0x96, 0x77, 0x60, 0x7f, 0xf6, 0xed, 0x8d, 0xb6, 0xf0, 0x1e,
	0x3c, 0xbb, 0x4b, 0x86, 0x50, 0xdb, 0xbf, 0xa6, 0xe1, 0x74, 0x40, 0xb9, 0x90, 0x5f, 0x22, 0xe8,
	0x4b, 0xfc, 0x18, 0x1e, 0x2c, 0xa7, 0x3c, 0xbd, 0xad, 0xd1, 0x3d, 0x39, 0x34, 0x6f, 0x55, 0x0c,
	0xe3, 0x23, 0xb4, 0x2d, 0x87, 0xf3, 0xed, 0x2a, 0x1d, 0xfb, 0xd7, 0xb4, 0xcf, 0x38, 0xaa, 0x2f,
	0x93, 0x49, 0x60, 0x25, 0x79, 0xff, 0x0e, 0x32, 0xa4, 0x96, 0x50, 0xe4, 0x83, 0xe5, 0xf2, 0x7d,
	0x4b, 0x45, 0x87, 0x8b, 0xd0, 0x0f, 0xa6, 0xe8, 0xe1, 0x72, 0x3e, 0xb3, 0xb1, 0xdb, 0x59, 0x2e,
	0xb4, 0x76, 0x10, 0x78, 0x53, 0x75, 0xd7, 0x33, 0x1a, 0xa1, 0x47, 0x77, 0x1f, 0x36, 0xbd, 0x72,
	0xd1, 0xe3, 0xfd, 0xdf, 0xc0, 0x56, 0x9f, 0xf1, 0x0f, 0x96, 0x08, 0xd9, 0x24, 0xdb, 0xf0, 0xbb,
	0xb0, 0x73, 0x17, 0x3e, 0x3c, 0x8c, 0xc3, 0x90, 0x72, 0x81, 0x0c, 0xfc, 0x15, 0x3c, 0xba, 0x53,
	0xa2, 0x47, 0x6f, 0x8e, 0x59, 0x18, 0x09, 0x94, 0x93, 0x79, 0xfb, 0x94, 0xc8, 0x80, 0xda, 0x3e,
	0x77, 0x50, 0xfe, 0xe0, 0x27, 0x50, 0xbc, 0x61, 0xea, 0x45, 0x86, 0xbf, 0x6a, 0x26, 0xff, 0x0b,
	0x35, 0xd3, 0xff, 0x85, 0x9a, 0x1d, 0x1e, 0x8f, 0x7f, 0x61, 0x79, 0x31, 0x3d, 0x0d, 0xe4, 0x6d,
	0x18, 0xd5, 0xff, 0xfa, 0xdb, 0xbc, 0x7a, 0x90, 0xac, 0x4a, 0x9d, 0x2e, 0x3f, 0xf8, 0x29, 0x94,
	0x94, 0xb6, 0x1f, 0x8b, 0xcf, 0x51, 0xff, 0x9b, 0x56, 0x57, 0x5b, 0x9e, 0xc6, 0xe2, 0xe0, 0x2d,
	0xd4, 0x94, 0xbe, 0x43, 0x2f, 0xe2, 0xd1, 0x67, 0xfa, 0xf0, 0x77, 0x6d, 0xa4, 0x22, 0x35, 0x8f,
	0xa4, 0x62, 0x97, 0x1f, 0x74, 0x61, 0x2d, 0x63, 0xe8, 0x33, 0xdd, 0xf9, 0x87, 0xb6, 0x54, 0x9d,
	0x59, 0x3a, 0x8d, 0xc5, 0x9b, 0x6f, 0xe0, 0x81, 0xed, 0x8f, 0x9b, 0x57, 0x94, 0x06, 0x57, 0x74,
	0xda, 0x74, 0xd4, 0x24, 0x53, 0x46, 0x6c, 0xdf, 0x7b, 0x53, 0x79, 0x47, 0x69, 0xf0, 0x8e, 0xaa,
	0x97, 0xdc, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xba, 0x23, 0x2d, 0x4c, 0x56, 0x13, 0x00, 0x00,
}

/* ADDED CONTENT HERE */


type RecoveryDeviceType int32
type WordRequestType int32


func (z *TxRequestSerializedType) SetSignatureIndex(x *uint32) {
	z.SignatureIndex = x
}

func (z *TxRequestSerializedType) SetSignature(x []byte) {
	z.Signature = x
}

func (z *TxRequestSerializedType) SetSerializedTx(x []byte) {
	z.SerializedTx = x
}

func (z *IdentityType) SetPort(x *string) {
	z.Port = x
}

func (z *IdentityType) SetPath(x *string) {
	z.Path = x
}

func (z *IdentityType) SetIndex(x *uint32) {
	z.Index = x
}

func (z *IdentityType) SetProto(x *string) {
	z.Proto = x
}

func (z *IdentityType) SetUser(x *string) {
	z.User = x
}

func (z *IdentityType) SetHost(x *string) {
	z.Host = x
}

func (z *MultisigRedeemScriptType) SetPubkeys(x []types.HDNodePathTyper) {
	l := len(x)
	xx := make([]*HDNodePathType, l)
	zx := make([]HDNodePathType, l)
	for i := 0; i < l; i++ {
		zx[i] = HDNodePathTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.Pubkeys = xx
}

func (z *MultisigRedeemScriptType) SetSignatures(x [][]byte) {
	z.Signatures = x
}

func (z *MultisigRedeemScriptType) SetM(x *uint32) {
	z.M = x
}

func (z *TxInputType) SetPrevHash(x []byte) {
	z.PrevHash = x
}

func (z *TxInputType) SetPrevIndex(x *uint32) {
	z.PrevIndex = x
}

func (z *TxInputType) SetScriptSig(x []byte) {
	z.ScriptSig = x
}

func (z *TxInputType) SetSequence(x *uint32) {
	z.Sequence = x
}

func (z *TxInputType) SetScriptType(x types.InputScriptTyper) {
	zx := InputScriptTyper2Type(x)
	z.ScriptType = &zx
}

func (z *TxInputType) SetMultisig(x types.MultisigRedeemScriptTyper) {
	zx := MultisigRedeemScriptTyper2Type(x)
	z.Multisig = &zx
}

func (z *TxInputType) SetAmount(x *uint64) {
	z.Amount = x
}

func (z *TxInputType) SetAddressN(x []uint32) {
	z.AddressN = x
}

func (z *TxOutputType) SetOpReturnData(x []byte) {
	z.OpReturnData = x
}

func (z *TxOutputType) SetAddressType(x types.OutputAddressTyper) {
	zx := OutputAddressTyper2Type(x)
	z.AddressType = &zx
}

func (z *TxOutputType) SetExchangeType(x types.ExchangeTyper) {
	zx := ExchangeTyper2Type(x)
	z.ExchangeType = &zx
}

func (z *TxOutputType) SetAddress(x *string) {
	z.Address = x
}

func (z *TxOutputType) SetAddressN(x []uint32) {
	z.AddressN = x
}

func (z *TxOutputType) SetAmount(x *uint64) {
	z.Amount = x
}

func (z *TxOutputType) SetScriptType(x types.OutputScriptTyper) {
	zx := OutputScriptTyper2Type(x)
	z.ScriptType = &zx
}

func (z *TxOutputType) SetMultisig(x types.MultisigRedeemScriptTyper) {
	zx := MultisigRedeemScriptTyper2Type(x)
	z.Multisig = &zx
}

func (z *HDNodeType) SetChainCode(x []byte) {
	z.ChainCode = x
}

func (z *HDNodeType) SetPrivateKey(x []byte) {
	z.PrivateKey = x
}

func (z *HDNodeType) SetPublicKey(x []byte) {
	z.PublicKey = x
}

func (z *HDNodeType) SetDepth(x *uint32) {
	z.Depth = x
}

func (z *HDNodeType) SetFingerprint(x *uint32) {
	z.Fingerprint = x
}

func (z *HDNodeType) SetChildNum(x *uint32) {
	z.ChildNum = x
}

func (z *CoinType) SetCoinName(x *string) {
	z.CoinName = x
}

func (z *CoinType) SetMaxfeeKb(x *uint64) {
	z.MaxfeeKb = x
}

func (z *CoinType) SetSignedMessageHeader(x *string) {
	z.SignedMessageHeader = x
}

func (z *CoinType) SetBip44AccountPath(x *uint32) {
	z.Bip44AccountPath = x
}

func (z *CoinType) SetCoinShortcut(x *string) {
	z.CoinShortcut = x
}

func (z *CoinType) SetAddressType(x *uint32) {
	z.AddressType = x
}

func (z *CoinType) SetAddressTypeP2Sh(x *uint32) {
	z.AddressTypeP2Sh = x
}

func (z *CoinType) SetAddressTypeP2Wpkh(x *uint32) {
	z.AddressTypeP2Wpkh = x
}

func (z *CoinType) SetAddressTypeP2Wsh(x *uint32) {
	z.AddressTypeP2Wsh = x
}

func (z *RawTransactionType) SetPayload(x []byte) {
	z.Payload = x
}

func (z *TxRequestDetailsType) SetExtraDataLen(x *uint32) {
	z.ExtraDataLen = x
}

func (z *TxRequestDetailsType) SetExtraDataOffset(x *uint32) {
	z.ExtraDataOffset = x
}

func (z *TxRequestDetailsType) SetRequestIndex(x *uint32) {
	z.RequestIndex = x
}

func (z *TxRequestDetailsType) SetTxHash(x []byte) {
	z.TxHash = x
}

func (z *HDNodePathType) SetNode(x types.HDNodeTyper) {
	zx := HDNodeTyper2Type(x)
	z.Node = &zx
}

func (z *HDNodePathType) SetAddressN(x []uint32) {
	z.AddressN = x
}

func (z *TransactionType) SetInputs(x []types.TxInputTyper) {
	l := len(x)
	xx := make([]*TxInputType, l)
	zx := make([]TxInputType, l)
	for i := 0; i < l; i++ {
		zx[i] = TxInputTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.Inputs = xx
}

func (z *TransactionType) SetOutputs(x []types.TxOutputTyper) {
	l := len(x)
	xx := make([]*TxOutputType, l)
	zx := make([]TxOutputType, l)
	for i := 0; i < l; i++ {
		zx[i] = TxOutputTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.Outputs = xx
}

func (z *TransactionType) SetExtraData(x []byte) {
	z.ExtraData = x
}

func (z *TransactionType) SetExtraDataLen(x *uint32) {
	z.ExtraDataLen = x
}

func (z *TransactionType) SetOutputsCnt(x *uint32) {
	z.OutputsCnt = x
}

func (z *TransactionType) SetVersion(x *uint32) {
	z.Version = x
}

func (z *TransactionType) SetBinOutputs(x []types.TxOutputBinTyper) {
	l := len(x)
	xx := make([]*TxOutputBinType, l)
	zx := make([]TxOutputBinType, l)
	for i := 0; i < l; i++ {
		zx[i] = TxOutputBinTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.BinOutputs = xx
}

func (z *TransactionType) SetLockTime(x *uint32) {
	z.LockTime = x
}

func (z *TransactionType) SetInputsCnt(x *uint32) {
	z.InputsCnt = x
}

func (z *PolicyType) SetPolicyName(x *string) {
	z.PolicyName = x
}

func (z *PolicyType) SetEnabled(x *bool) {
	z.Enabled = x
}

func (z *ExchangeType) SetSignedExchangeResponse(x *exchange.SignedExchangeResponse) {
	z.SignedExchangeResponse = x
}

func (z *ExchangeType) SetWithdrawalCoinName(x *string) {
	z.WithdrawalCoinName = x
}

func (z *ExchangeType) SetWithdrawalAddressN(x []uint32) {
	z.WithdrawalAddressN = x
}

func (z *ExchangeType) SetReturnAddressN(x []uint32) {
	z.ReturnAddressN = x
}

func (z *TxOutputBinType) SetScriptPubkey(x []byte) {
	z.ScriptPubkey = x
}

func (z *TxOutputBinType) SetAmount(x *uint64) {
	z.Amount = x
}

func (*RecoveryDeviceType) String() string {
	var x string
	return x
}
func (*RecoveryDeviceType) UnmarshalJSON(data []byte) error {
	var x error
	return x
}
func (*WordRequestType) String() string {
	var x string
	return x
}
func (*WordRequestType) UnmarshalJSON(data []byte) error {
	var x error
	return x
}

type Getter struct{}

func (*Getter) GetIdentityType() types.IdentityTyper {
	var x IdentityType
	return &x
}

func (*Getter) GetTransactionType() types.TransactionTyper {
	var x TransactionType
	return &x
}

func (*Getter) GetRawTransactionType() types.RawTransactionTyper {
	var x RawTransactionType
	return &x
}

func (*Getter) GetTxRequestDetailsType() types.TxRequestDetailsTyper {
	var x TxRequestDetailsType
	return &x
}

func (*Getter) GetMultisigRedeemScriptType() types.MultisigRedeemScriptTyper {
	var x MultisigRedeemScriptType
	return &x
}

func (*Getter) GetTxOutputType() types.TxOutputTyper {
	var x TxOutputType
	return &x
}

func (*Getter) GetTxRequestSerializedType() types.TxRequestSerializedTyper {
	var x TxRequestSerializedType
	return &x
}

func (*Getter) GetPolicyType() types.PolicyTyper {
	var x PolicyType
	return &x
}

func (*Getter) GetTxOutputBinType() types.TxOutputBinTyper {
	var x TxOutputBinType
	return &x
}

func (*Getter) GetHDNodeType() types.HDNodeTyper {
	var x HDNodeType
	return &x
}

func (*Getter) GetCoinType() types.CoinTyper {
	var x CoinType
	return &x
}

func (*Getter) GetTxInputType() types.TxInputTyper {
	var x TxInputType
	return &x
}

func (*Getter) GetHDNodePathType() types.HDNodePathTyper {
	var x HDNodePathType
	return &x
}

func (*Getter) GetExchangeType() types.ExchangeTyper {
	var x ExchangeType
	return &x
}

func (*Getter) GetButtonRequestType() types.ButtonRequestTyper {
	var x ButtonRequestType
	return &x
}

func (*Getter) GetFailureType() types.FailureTyper {
	var x FailureType
	return &x
}

func (*Getter) GetInputScriptType() types.InputScriptTyper {
	var x InputScriptType
	return &x
}

func (*Getter) GetOutputAddressType() types.OutputAddressTyper {
	var x OutputAddressType
	return &x
}

func (*Getter) GetOutputScriptType() types.OutputScriptTyper {
	var x OutputScriptType
	return &x
}

func (*Getter) GetPinMatrixRequestType() types.PinMatrixRequestTyper {
	var x PinMatrixRequestType
	return &x
}

func (*Getter) GetRecoveryDeviceType() types.RecoveryDeviceTyper {
	var x RecoveryDeviceType
	return &x
}

func (*Getter) GetRequestType() types.RequestTyper {
	var x RequestType
	return &x
}

func (*Getter) GetWordRequestType() types.WordRequestTyper {
	var x WordRequestType
	return &x
}






func TxOutputBinTyper2Type(x types.TxOutputBinTyper) TxOutputBinType {
	var z TxOutputBinType
	x0 := x.GetAmount()
	z.Amount = &x0
	x1 := x.GetScriptPubkey()
	z.ScriptPubkey = x1
	return z
}

func TransactionTyper2Type(x types.TransactionTyper) TransactionType {
	var z TransactionType
	xx0 := x.GetInputs()
	l0 := len(xx0)
	x0 := make([]*TxInputType, l0)
	for k, v := range xx0 {
		xxx0 := TxInputTyper2Type(v)
		x0[k] = &xxx0
	}
	z.Inputs = x0
	xx1 := x.GetOutputs()
	l1 := len(xx1)
	x1 := make([]*TxOutputType, l1)
	for k, v := range xx1 {
		xxx1 := TxOutputTyper2Type(v)
		x1[k] = &xxx1
	}
	z.Outputs = x1
	x2 := x.GetExtraData()
	z.ExtraData = x2
	x3 := x.GetExtraDataLen()
	z.ExtraDataLen = &x3
	x4 := x.GetVersion()
	z.Version = &x4
	xx5 := x.GetBinOutputs()
	l5 := len(xx5)
	x5 := make([]*TxOutputBinType, l5)
	for k, v := range xx5 {
		xxx5 := TxOutputBinTyper2Type(v)
		x5[k] = &xxx5
	}
	z.BinOutputs = x5
	x6 := x.GetLockTime()
	z.LockTime = &x6
	x7 := x.GetInputsCnt()
	z.InputsCnt = &x7
	x8 := x.GetOutputsCnt()
	z.OutputsCnt = &x8
	return z
}

func PolicyTyper2Type(x types.PolicyTyper) PolicyType {
	var z PolicyType
	x0 := x.GetPolicyName()
	z.PolicyName = &x0
	x1 := x.GetEnabled()
	z.Enabled = &x1
	return z
}

func ExchangeTyper2Type(x types.ExchangeTyper) ExchangeType {
	var z ExchangeType
	x0 := x.GetSignedExchangeResponse()
	z.SignedExchangeResponse = x0
	x1 := x.GetWithdrawalCoinName()
	z.WithdrawalCoinName = &x1
	x2 := x.GetWithdrawalAddressN()
	z.WithdrawalAddressN = x2
	x3 := x.GetReturnAddressN()
	z.ReturnAddressN = x3
	return z
}

func MultisigRedeemScriptTyper2Type(x types.MultisigRedeemScriptTyper) MultisigRedeemScriptType {
	var z MultisigRedeemScriptType
	xx0 := x.GetPubkeys()
	l0 := len(xx0)
	x0 := make([]*HDNodePathType, l0)
	for k, v := range xx0 {
		xxx0 := HDNodePathTyper2Type(v)
		x0[k] = &xxx0
	}
	z.Pubkeys = x0
	x1 := x.GetSignatures()
	z.Signatures = x1
	x2 := x.GetM()
	z.M = &x2
	return z
}

func TxRequestSerializedTyper2Type(x types.TxRequestSerializedTyper) TxRequestSerializedType {
	var z TxRequestSerializedType
	x0 := x.GetSignatureIndex()
	z.SignatureIndex = &x0
	x1 := x.GetSignature()
	z.Signature = x1
	x2 := x.GetSerializedTx()
	z.SerializedTx = x2
	return z
}

func IdentityTyper2Type(x types.IdentityTyper) IdentityType {
	var z IdentityType
	x0 := x.GetProto()
	z.Proto = &x0
	x1 := x.GetUser()
	z.User = &x1
	x2 := x.GetHost()
	z.Host = &x2
	x3 := x.GetPort()
	z.Port = &x3
	x4 := x.GetPath()
	z.Path = &x4
	x5 := x.GetIndex()
	z.Index = &x5
	return z
}

func HDNodeTyper2Type(x types.HDNodeTyper) HDNodeType {
	var z HDNodeType
	x0 := x.GetDepth()
	z.Depth = &x0
	x1 := x.GetFingerprint()
	z.Fingerprint = &x1
	x2 := x.GetChildNum()
	z.ChildNum = &x2
	x3 := x.GetChainCode()
	z.ChainCode = x3
	x4 := x.GetPrivateKey()
	z.PrivateKey = x4
	x5 := x.GetPublicKey()
	z.PublicKey = x5
	return z
}

func TxInputTyper2Type(x types.TxInputTyper) TxInputType {
	var z TxInputType
	x0 := x.GetPrevHash()
	z.PrevHash = x0
	x1 := x.GetPrevIndex()
	z.PrevIndex = &x1
	x2 := x.GetScriptSig()
	z.ScriptSig = x2
	x3 := x.GetSequence()
	z.Sequence = &x3
	x4 := InputScriptTyper2Type(x.GetScriptType())
	z.ScriptType = &x4
	x5 := MultisigRedeemScriptTyper2Type(x.GetMultisig())
	z.Multisig = &x5
	x6 := x.GetAmount()
	z.Amount = &x6
	x7 := x.GetAddressN()
	z.AddressN = x7
	return z
}

func TxOutputTyper2Type(x types.TxOutputTyper) TxOutputType {
	var z TxOutputType
	x0 := x.GetOpReturnData()
	z.OpReturnData = x0
	x1 := OutputAddressTyper2Type(x.GetAddressType())
	z.AddressType = &x1
	x2 := ExchangeTyper2Type(x.GetExchangeType())
	z.ExchangeType = &x2
	x3 := x.GetAddress()
	z.Address = &x3
	x4 := x.GetAddressN()
	z.AddressN = x4
	x5 := x.GetAmount()
	z.Amount = &x5
	x6 := OutputScriptTyper2Type(x.GetScriptType())
	z.ScriptType = &x6
	x7 := MultisigRedeemScriptTyper2Type(x.GetMultisig())
	z.Multisig = &x7
	return z
}

func HDNodePathTyper2Type(x types.HDNodePathTyper) HDNodePathType {
	var z HDNodePathType
	x0 := HDNodeTyper2Type(x.GetNode())
	z.Node = &x0
	x1 := x.GetAddressN()
	z.AddressN = x1
	return z
}

func CoinTyper2Type(x types.CoinTyper) CoinType {
	var z CoinType
	x0 := x.GetSignedMessageHeader()
	z.SignedMessageHeader = &x0
	x1 := x.GetBip44AccountPath()
	z.Bip44AccountPath = &x1
	x2 := x.GetCoinName()
	z.CoinName = &x2
	x3 := x.GetMaxfeeKb()
	z.MaxfeeKb = &x3
	x4 := x.GetAddressTypeP2Sh()
	z.AddressTypeP2Sh = &x4
	x5 := x.GetAddressTypeP2Wpkh()
	z.AddressTypeP2Wpkh = &x5
	x6 := x.GetAddressTypeP2Wsh()
	z.AddressTypeP2Wsh = &x6
	x7 := x.GetCoinShortcut()
	z.CoinShortcut = &x7
	x8 := x.GetAddressType()
	z.AddressType = &x8
	return z
}

func RawTransactionTyper2Type(x types.RawTransactionTyper) RawTransactionType {
	var z RawTransactionType
	x0 := x.GetPayload()
	z.Payload = x0
	return z
}

func TxRequestDetailsTyper2Type(x types.TxRequestDetailsTyper) TxRequestDetailsType {
	var z TxRequestDetailsType
	x0 := x.GetRequestIndex()
	z.RequestIndex = &x0
	x1 := x.GetTxHash()
	z.TxHash = x1
	x2 := x.GetExtraDataLen()
	z.ExtraDataLen = &x2
	x3 := x.GetExtraDataOffset()
	z.ExtraDataOffset = &x3
	return z
}

func OutputAddressTyper2Type(x types.OutputAddressTyper) OutputAddressType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return OutputAddressType(int32(tmp))
}

func ButtonRequestTyper2Type(x types.ButtonRequestTyper) ButtonRequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return ButtonRequestType(int32(tmp))
}

func PinMatrixRequestTyper2Type(x types.PinMatrixRequestTyper) PinMatrixRequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return PinMatrixRequestType(int32(tmp))
}

func FailureTyper2Type(x types.FailureTyper) FailureType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return FailureType(int32(tmp))
}

func OutputScriptTyper2Type(x types.OutputScriptTyper) OutputScriptType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return OutputScriptType(int32(tmp))
}

func InputScriptTyper2Type(x types.InputScriptTyper) InputScriptType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return InputScriptType(int32(tmp))
}

func RequestTyper2Type(x types.RequestTyper) RequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return RequestType(int32(tmp))
}
