// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	HDNodeType
	HDNodePathType
	CoinType
	MultisigRedeemScriptType
	TxInputType
	TxOutputType
	TxOutputBinType
	TransactionType
	TxRequestDetailsType
	TxRequestSerializedType
	IdentityType
*/
package types

import (
	fmt "fmt"
	"strconv"

	proto "github.com/golang/protobuf/proto"

	math "math"

	google_protobuf "github.com/conejoninja/cerrojo/pb/google/protobuf"
	"github.com/conejoninja/cerrojo/pb/exchange"
	types "github.com/conejoninja/cerrojo/pb/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Type of failures returned by Failure message
// @used_in Failure
type FailureType int32

const (
	FailureType_Failure_UnexpectedMessage FailureType = 1
	FailureType_Failure_ButtonExpected    FailureType = 2
	FailureType_Failure_SyntaxError       FailureType = 3
	FailureType_Failure_ActionCancelled   FailureType = 4
	FailureType_Failure_PinExpected       FailureType = 5
	FailureType_Failure_PinCancelled      FailureType = 6
	FailureType_Failure_PinInvalid        FailureType = 7
	FailureType_Failure_InvalidSignature  FailureType = 8
	FailureType_Failure_Other             FailureType = 9
	FailureType_Failure_NotEnoughFunds    FailureType = 10
	FailureType_Failure_NotInitialized    FailureType = 11
	FailureType_Failure_FirmwareError     FailureType = 99
)

var FailureType_name = map[int32]string{
	1:  "Failure_UnexpectedMessage",
	2:  "Failure_ButtonExpected",
	3:  "Failure_SyntaxError",
	4:  "Failure_ActionCancelled",
	5:  "Failure_PinExpected",
	6:  "Failure_PinCancelled",
	7:  "Failure_PinInvalid",
	8:  "Failure_InvalidSignature",
	9:  "Failure_Other",
	10: "Failure_NotEnoughFunds",
	11: "Failure_NotInitialized",
	99: "Failure_FirmwareError",
}
var FailureType_value = map[string]int32{
	"Failure_UnexpectedMessage": 1,
	"Failure_ButtonExpected":    2,
	"Failure_SyntaxError":       3,
	"Failure_ActionCancelled":   4,
	"Failure_PinExpected":       5,
	"Failure_PinCancelled":      6,
	"Failure_PinInvalid":        7,
	"Failure_InvalidSignature":  8,
	"Failure_Other":             9,
	"Failure_NotEnoughFunds":    10,
	"Failure_NotInitialized":    11,
	"Failure_FirmwareError":     99,
}

func (x FailureType) Enum() *FailureType {
	p := new(FailureType)
	*p = x
	return p
}
func (x FailureType) String() string {
	return proto.EnumName(FailureType_name, int32(x))
}
func (x *FailureType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FailureType_value, data, "FailureType")
	if err != nil {
		return err
	}
	*x = FailureType(value)
	return nil
}
func (FailureType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Type of script which will be used for transaction output
// @used_in TxOutputType
type OutputScriptType int32

const (
	OutputScriptType_PAYTOADDRESS     OutputScriptType = 0
	OutputScriptType_PAYTOSCRIPTHASH  OutputScriptType = 1
	OutputScriptType_PAYTOMULTISIG    OutputScriptType = 2
	OutputScriptType_PAYTOOPRETURN    OutputScriptType = 3
	OutputScriptType_PAYTOWITNESS     OutputScriptType = 4
	OutputScriptType_PAYTOP2SHWITNESS OutputScriptType = 5
)

var OutputScriptType_name = map[int32]string{
	0: "PAYTOADDRESS",
	1: "PAYTOSCRIPTHASH",
	2: "PAYTOMULTISIG",
	3: "PAYTOOPRETURN",
	4: "PAYTOWITNESS",
	5: "PAYTOP2SHWITNESS",
}
var OutputScriptType_value = map[string]int32{
	"PAYTOADDRESS":     0,
	"PAYTOSCRIPTHASH":  1,
	"PAYTOMULTISIG":    2,
	"PAYTOOPRETURN":    3,
	"PAYTOWITNESS":     4,
	"PAYTOP2SHWITNESS": 5,
}

func (x OutputScriptType) Enum() *OutputScriptType {
	p := new(OutputScriptType)
	*p = x
	return p
}
func (x OutputScriptType) String() string {
	return proto.EnumName(OutputScriptType_name, int32(x))
}
func (x *OutputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputScriptType_value, data, "OutputScriptType")
	if err != nil {
		return err
	}
	*x = OutputScriptType(value)
	return nil
}
func (OutputScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
// Type of script which will be used for transaction output
// @used_in TxInputType
type InputScriptType int32

const (
	InputScriptType_SPENDADDRESS     InputScriptType = 0
	InputScriptType_SPENDMULTISIG    InputScriptType = 1
	InputScriptType_EXTERNAL         InputScriptType = 2
	InputScriptType_SPENDWITNESS     InputScriptType = 3
	InputScriptType_SPENDP2SHWITNESS InputScriptType = 4
)

var InputScriptType_name = map[int32]string{
	0: "SPENDADDRESS",
	1: "SPENDMULTISIG",
	2: "EXTERNAL",
	3: "SPENDWITNESS",
	4: "SPENDP2SHWITNESS",
}
var InputScriptType_value = map[string]int32{
	"SPENDADDRESS":     0,
	"SPENDMULTISIG":    1,
	"EXTERNAL":         2,
	"SPENDWITNESS":     3,
	"SPENDP2SHWITNESS": 4,
}

func (x InputScriptType) Enum() *InputScriptType {
	p := new(InputScriptType)
	*p = x
	return p
}
func (x InputScriptType) String() string {
	return proto.EnumName(InputScriptType_name, int32(x))
}
func (x *InputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InputScriptType_value, data, "InputScriptType")
	if err != nil {
		return err
	}
	*x = InputScriptType(value)
	return nil
}
func (InputScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// *
// Type of information required by transaction signing process
// @used_in TxRequest
type RequestType int32

const (
	RequestType_TXINPUT     RequestType = 0
	RequestType_TXOUTPUT    RequestType = 1
	RequestType_TXMETA      RequestType = 2
	RequestType_TXFINISHED  RequestType = 3
	RequestType_TXEXTRADATA RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "TXINPUT",
	1: "TXOUTPUT",
	2: "TXMETA",
	3: "TXFINISHED",
	4: "TXEXTRADATA",
}
var RequestType_value = map[string]int32{
	"TXINPUT":     0,
	"TXOUTPUT":    1,
	"TXMETA":      2,
	"TXFINISHED":  3,
	"TXEXTRADATA": 4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// *
// Type of button request
// @used_in ButtonRequest
type ButtonRequestType int32

const (
	ButtonRequestType_ButtonRequest_Other            ButtonRequestType = 1
	ButtonRequestType_ButtonRequest_FeeOverThreshold ButtonRequestType = 2
	ButtonRequestType_ButtonRequest_ConfirmOutput    ButtonRequestType = 3
	ButtonRequestType_ButtonRequest_ResetDevice      ButtonRequestType = 4
	ButtonRequestType_ButtonRequest_ConfirmWord      ButtonRequestType = 5
	ButtonRequestType_ButtonRequest_WipeDevice       ButtonRequestType = 6
	ButtonRequestType_ButtonRequest_ProtectCall      ButtonRequestType = 7
	ButtonRequestType_ButtonRequest_SignTx           ButtonRequestType = 8
	ButtonRequestType_ButtonRequest_FirmwareCheck    ButtonRequestType = 9
	ButtonRequestType_ButtonRequest_Address          ButtonRequestType = 10
	ButtonRequestType_ButtonRequest_PublicKey        ButtonRequestType = 11
)

var ButtonRequestType_name = map[int32]string{
	1:  "ButtonRequest_Other",
	2:  "ButtonRequest_FeeOverThreshold",
	3:  "ButtonRequest_ConfirmOutput",
	4:  "ButtonRequest_ResetDevice",
	5:  "ButtonRequest_ConfirmWord",
	6:  "ButtonRequest_WipeDevice",
	7:  "ButtonRequest_ProtectCall",
	8:  "ButtonRequest_SignTx",
	9:  "ButtonRequest_FirmwareCheck",
	10: "ButtonRequest_Address",
	11: "ButtonRequest_PublicKey",
}
var ButtonRequestType_value = map[string]int32{
	"ButtonRequest_Other":            1,
	"ButtonRequest_FeeOverThreshold": 2,
	"ButtonRequest_ConfirmOutput":    3,
	"ButtonRequest_ResetDevice":      4,
	"ButtonRequest_ConfirmWord":      5,
	"ButtonRequest_WipeDevice":       6,
	"ButtonRequest_ProtectCall":      7,
	"ButtonRequest_SignTx":           8,
	"ButtonRequest_FirmwareCheck":    9,
	"ButtonRequest_Address":          10,
	"ButtonRequest_PublicKey":        11,
}

func (x ButtonRequestType) Enum() *ButtonRequestType {
	p := new(ButtonRequestType)
	*p = x
	return p
}
func (x ButtonRequestType) String() string {
	return proto.EnumName(ButtonRequestType_name, int32(x))
}
func (x *ButtonRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ButtonRequestType_value, data, "ButtonRequestType")
	if err != nil {
		return err
	}
	*x = ButtonRequestType(value)
	return nil
}
func (ButtonRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// *
// Type of PIN request
// @used_in PinMatrixRequest
type PinMatrixRequestType int32

const (
	PinMatrixRequestType_PinMatrixRequestType_Current   PinMatrixRequestType = 1
	PinMatrixRequestType_PinMatrixRequestType_NewFirst  PinMatrixRequestType = 2
	PinMatrixRequestType_PinMatrixRequestType_NewSecond PinMatrixRequestType = 3
)

var PinMatrixRequestType_name = map[int32]string{
	1: "PinMatrixRequestType_Current",
	2: "PinMatrixRequestType_NewFirst",
	3: "PinMatrixRequestType_NewSecond",
}
var PinMatrixRequestType_value = map[string]int32{
	"PinMatrixRequestType_Current":   1,
	"PinMatrixRequestType_NewFirst":  2,
	"PinMatrixRequestType_NewSecond": 3,
}

func (x PinMatrixRequestType) Enum() *PinMatrixRequestType {
	p := new(PinMatrixRequestType)
	*p = x
	return p
}
func (x PinMatrixRequestType) String() string {
	return proto.EnumName(PinMatrixRequestType_name, int32(x))
}
func (x *PinMatrixRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PinMatrixRequestType_value, data, "PinMatrixRequestType")
	if err != nil {
		return err
	}
	*x = PinMatrixRequestType(value)
	return nil
}
func (PinMatrixRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// *
// Type of recovery procedure. These should be used as bitmask, e.g.,
// `RecoveryDeviceType_ScrambledWords | RecoveryDeviceType_Matrix`
// listing every method supported by the host computer.
//
// Note that ScrambledWords must be supported by every implementation
// for backward compatibility; there is no way to not support it.
//
// @used_in RecoveryDevice
type RecoveryDeviceType int32

const (
	// use powers of two when extending this field
	RecoveryDeviceType_RecoveryDeviceType_ScrambledWords RecoveryDeviceType = 0
	RecoveryDeviceType_RecoveryDeviceType_Matrix         RecoveryDeviceType = 1
)

var RecoveryDeviceType_name = map[int32]string{
	0: "RecoveryDeviceType_ScrambledWords",
	1: "RecoveryDeviceType_Matrix",
}
var RecoveryDeviceType_value = map[string]int32{
	"RecoveryDeviceType_ScrambledWords": 0,
	"RecoveryDeviceType_Matrix":         1,
}

func (x RecoveryDeviceType) Enum() *RecoveryDeviceType {
	p := new(RecoveryDeviceType)
	*p = x
	return p
}
func (x RecoveryDeviceType) String() string {
	return proto.EnumName(RecoveryDeviceType_name, int32(x))
}
func (x *RecoveryDeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RecoveryDeviceType_value, data, "RecoveryDeviceType")
	if err != nil {
		return err
	}
	*x = RecoveryDeviceType(value)
	return nil
}
func (RecoveryDeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// *
// Type of Recovery Word request
// @used_in WordRequest
type WordRequestType int32

const (
	WordRequestType_WordRequestType_Plain   WordRequestType = 0
	WordRequestType_WordRequestType_Matrix9 WordRequestType = 1
	WordRequestType_WordRequestType_Matrix6 WordRequestType = 2
)

var WordRequestType_name = map[int32]string{
	0: "WordRequestType_Plain",
	1: "WordRequestType_Matrix9",
	2: "WordRequestType_Matrix6",
}
var WordRequestType_value = map[string]int32{
	"WordRequestType_Plain":   0,
	"WordRequestType_Matrix9": 1,
	"WordRequestType_Matrix6": 2,
}

func (x WordRequestType) Enum() *WordRequestType {
	p := new(WordRequestType)
	*p = x
	return p
}
func (x WordRequestType) String() string {
	return proto.EnumName(WordRequestType_name, int32(x))
}
func (x *WordRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WordRequestType_value, data, "WordRequestType")
	if err != nil {
		return err
	}
	*x = WordRequestType(value)
	return nil
}
func (WordRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// *
// Structure representing BIP32 (hierarchical deterministic) node
// Used for imports of private key into the device and exporting public key out of device
// @used_in PublicKey
// @used_in LoadDevice
// @used_in DebugLinkState
// @used_in Storage
type HDNodeType struct {
	Depth            *uint32 `protobuf:"varint,1,req,name=depth" json:"depth,omitempty"`
	Fingerprint      *uint32 `protobuf:"varint,2,req,name=fingerprint" json:"fingerprint,omitempty"`
	ChildNum         *uint32 `protobuf:"varint,3,req,name=child_num,json=childNum" json:"child_num,omitempty"`
	ChainCode        []byte  `protobuf:"bytes,4,req,name=chain_code,json=chainCode" json:"chain_code,omitempty"`
	PrivateKey       []byte  `protobuf:"bytes,5,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,6,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HDNodeType) Reset()                    { *m = HDNodeType{} }
func (m *HDNodeType) String() string            { return proto.CompactTextString(m) }
func (*HDNodeType) ProtoMessage()               {}
func (*HDNodeType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HDNodeType) GetDepth() uint32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *HDNodeType) GetFingerprint() uint32 {
	if m != nil && m.Fingerprint != nil {
		return *m.Fingerprint
	}
	return 0
}

func (m *HDNodeType) GetChildNum() uint32 {
	if m != nil && m.ChildNum != nil {
		return *m.ChildNum
	}
	return 0
}

func (m *HDNodeType) GetChainCode() []byte {
	if m != nil {
		return m.ChainCode
	}
	return nil
}

func (m *HDNodeType) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *HDNodeType) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type HDNodePathType struct {
	Node             *HDNodeType `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	AddressN         []uint32    `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *HDNodePathType) Reset()                    { *m = HDNodePathType{} }
func (m *HDNodePathType) String() string            { return proto.CompactTextString(m) }
func (*HDNodePathType) ProtoMessage()               {}
func (*HDNodePathType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HDNodePathType) GetNode() types.HDNodeTyper {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HDNodePathType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

// *
// Structure representing Coin
// @used_in Features
type CoinType struct {
	CoinName            *string `protobuf:"bytes,1,opt,name=coin_name,json=coinName" json:"coin_name,omitempty"`
	CoinShortcut        *string `protobuf:"bytes,2,opt,name=coin_shortcut,json=coinShortcut" json:"coin_shortcut,omitempty"`
	AddressType         *uint32 `protobuf:"varint,3,opt,name=address_type,json=addressType,def=0" json:"address_type,omitempty"`
	MaxfeeKb            *uint64 `protobuf:"varint,4,opt,name=maxfee_kb,json=maxfeeKb" json:"maxfee_kb,omitempty"`
	AddressTypeP2Sh     *uint32 `protobuf:"varint,5,opt,name=address_type_p2sh,json=addressTypeP2sh,def=5" json:"address_type_p2sh,omitempty"`
	AddressTypeP2Wpkh   *uint32 `protobuf:"varint,6,opt,name=address_type_p2wpkh,json=addressTypeP2wpkh,def=6" json:"address_type_p2wpkh,omitempty"`
	AddressTypeP2Wsh    *uint32 `protobuf:"varint,7,opt,name=address_type_p2wsh,json=addressTypeP2wsh,def=10" json:"address_type_p2wsh,omitempty"`
	SignedMessageHeader *string `protobuf:"bytes,8,opt,name=signed_message_header,json=signedMessageHeader" json:"signed_message_header,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CoinType) Reset()                    { *m = CoinType{} }
func (m *CoinType) String() string            { return proto.CompactTextString(m) }
func (*CoinType) ProtoMessage()               {}
func (*CoinType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_CoinType_AddressType uint32 = 0
const Default_CoinType_AddressTypeP2Sh uint32 = 5
const Default_CoinType_AddressTypeP2Wpkh uint32 = 6
const Default_CoinType_AddressTypeP2Wsh uint32 = 10

func (m *CoinType) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return ""
}

func (m *CoinType) GetCoinShortcut() string {
	if m != nil && m.CoinShortcut != nil {
		return *m.CoinShortcut
	}
	return ""
}

func (m *CoinType) GetAddressType() uint32 {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return Default_CoinType_AddressType
}

func (m *CoinType) GetMaxfeeKb() uint64 {
	if m != nil && m.MaxfeeKb != nil {
		return *m.MaxfeeKb
	}
	return 0
}

func (m *CoinType) GetAddressTypeP2Sh() uint32 {
	if m != nil && m.AddressTypeP2Sh != nil {
		return *m.AddressTypeP2Sh
	}
	return Default_CoinType_AddressTypeP2Sh
}

func (m *CoinType) GetAddressTypeP2Wpkh() uint32 {
	if m != nil && m.AddressTypeP2Wpkh != nil {
		return *m.AddressTypeP2Wpkh
	}
	return Default_CoinType_AddressTypeP2Wpkh
}

func (m *CoinType) GetAddressTypeP2Wsh() uint32 {
	if m != nil && m.AddressTypeP2Wsh != nil {
		return *m.AddressTypeP2Wsh
	}
	return Default_CoinType_AddressTypeP2Wsh
}

func (m *CoinType) GetSignedMessageHeader() string {
	if m != nil && m.SignedMessageHeader != nil {
		return *m.SignedMessageHeader
	}
	return ""
}

// *
// Type of redeem script used in input
// @used_in TxInputType
type MultisigRedeemScriptType struct {
	Pubkeys          []*HDNodePathType `protobuf:"bytes,1,rep,name=pubkeys" json:"pubkeys,omitempty"`
	Signatures       [][]byte          `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
	M                *uint32           `protobuf:"varint,3,opt,name=m" json:"m,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MultisigRedeemScriptType) Reset()                    { *m = MultisigRedeemScriptType{} }
func (m *MultisigRedeemScriptType) String() string            { return proto.CompactTextString(m) }
func (*MultisigRedeemScriptType) ProtoMessage()               {}
func (*MultisigRedeemScriptType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MultisigRedeemScriptType) GetPubkeys() []types.HDNodePathTyper {
	if m != nil {
		l := len(m.Pubkeys)
		z := make([]types.HDNodePathTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.Pubkeys[i]
		}
		return z
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetM() uint32 {
	if m != nil && m.M != nil {
		return *m.M
	}
	return 0
}

// *
// Structure representing transaction input
// @used_in SimpleSignTx
// @used_in TransactionType
type TxInputType struct {
	AddressN         []uint32                  `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	PrevHash         []byte                    `protobuf:"bytes,2,req,name=prev_hash,json=prevHash" json:"prev_hash,omitempty"`
	PrevIndex        *uint32                   `protobuf:"varint,3,req,name=prev_index,json=prevIndex" json:"prev_index,omitempty"`
	ScriptSig        []byte                    `protobuf:"bytes,4,opt,name=script_sig,json=scriptSig" json:"script_sig,omitempty"`
	Sequence         *uint32                   `protobuf:"varint,5,opt,name=sequence,def=4294967295" json:"sequence,omitempty"`
	ScriptType       *InputScriptType          `protobuf:"varint,6,opt,name=script_type,json=scriptType,enum=InputScriptType,def=0" json:"script_type,omitempty"`
	Multisig         *MultisigRedeemScriptType `protobuf:"bytes,7,opt,name=multisig" json:"multisig,omitempty"`
	Amount           *uint64                   `protobuf:"varint,8,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *TxInputType) Reset()                    { *m = TxInputType{} }
func (m *TxInputType) String() string            { return proto.CompactTextString(m) }
func (*TxInputType) ProtoMessage()               {}
func (*TxInputType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_TxInputType_Sequence uint32 = 4294967295
const Default_TxInputType_ScriptType InputScriptType = InputScriptType_SPENDADDRESS

func (m *TxInputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxInputType) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *TxInputType) GetPrevIndex() uint32 {
	if m != nil && m.PrevIndex != nil {
		return *m.PrevIndex
	}
	return 0
}

func (m *TxInputType) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

func (m *TxInputType) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return Default_TxInputType_Sequence
}

func (m *TxInputType) GetScriptType() types.InputScriptTyper {
	if m != nil && m.ScriptType != nil {
		return m.ScriptType
	}
	x := InputScriptType(Default_TxInputType_ScriptType)
	return &x
}

func (m *TxInputType) GetMultisig() types.MultisigRedeemScriptTyper {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxInputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

// *
// Structure representing transaction output
// @used_in SimpleSignTx
// @used_in TransactionType
type TxOutputType struct {
	Address          *string                   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	AddressN         []uint32                  `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Amount           *uint64                   `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	ScriptType       *OutputScriptType         `protobuf:"varint,4,req,name=script_type,json=scriptType,enum=OutputScriptType" json:"script_type,omitempty"`
	Multisig         *MultisigRedeemScriptType `protobuf:"bytes,5,opt,name=multisig" json:"multisig,omitempty"`
	OpReturnData     []byte                    `protobuf:"bytes,6,opt,name=op_return_data,json=opReturnData" json:"op_return_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *TxOutputType) Reset()                    { *m = TxOutputType{} }
func (m *TxOutputType) String() string            { return proto.CompactTextString(m) }
func (*TxOutputType) ProtoMessage()               {}
func (*TxOutputType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TxOutputType) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *TxOutputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxOutputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputType) GetScriptType() types.OutputScriptTyper {
	if m != nil && m.ScriptType != nil {
		x := OutputScriptType(*m.ScriptType)
		return &x
	}
	x :=  OutputScriptType(OutputScriptType_PAYTOADDRESS)
	return &x
}

func (m *TxOutputType) GetMultisig() types.MultisigRedeemScriptTyper {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxOutputType) GetOpReturnData() []byte {
	if m != nil {
		return m.OpReturnData
	}
	return nil
}

// *
// Structure representing compiled transaction output
// @used_in TransactionType
type TxOutputBinType struct {
	Amount           *uint64 `protobuf:"varint,1,req,name=amount" json:"amount,omitempty"`
	ScriptPubkey     []byte  `protobuf:"bytes,2,req,name=script_pubkey,json=scriptPubkey" json:"script_pubkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxOutputBinType) Reset()                    { *m = TxOutputBinType{} }
func (m *TxOutputBinType) String() string            { return proto.CompactTextString(m) }
func (*TxOutputBinType) ProtoMessage()               {}
func (*TxOutputBinType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TxOutputBinType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputBinType) GetScriptPubkey() []byte {
	if m != nil {
		return m.ScriptPubkey
	}
	return nil
}

// *
// Structure representing transaction
// @used_in SimpleSignTx
type TransactionType struct {
	Version          *uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Inputs           []*TxInputType     `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
	BinOutputs       []*TxOutputBinType `protobuf:"bytes,3,rep,name=bin_outputs,json=binOutputs" json:"bin_outputs,omitempty"`
	Outputs          []*TxOutputType    `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	LockTime         *uint32            `protobuf:"varint,4,opt,name=lock_time,json=lockTime" json:"lock_time,omitempty"`
	InputsCnt        *uint32            `protobuf:"varint,6,opt,name=inputs_cnt,json=inputsCnt" json:"inputs_cnt,omitempty"`
	OutputsCnt       *uint32            `protobuf:"varint,7,opt,name=outputs_cnt,json=outputsCnt" json:"outputs_cnt,omitempty"`
	ExtraData        []byte             `protobuf:"bytes,8,opt,name=extra_data,json=extraData" json:"extra_data,omitempty"`
	ExtraDataLen     *uint32            `protobuf:"varint,9,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *TransactionType) Reset()                    { *m = TransactionType{} }
func (m *TransactionType) String() string            { return proto.CompactTextString(m) }
func (*TransactionType) ProtoMessage()               {}
func (*TransactionType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TransactionType) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *TransactionType) GetInputs() []types.TxInputTyper {
	if m != nil {
		l := len(m.Inputs)
		z := make([]types.TxInputTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.Inputs[i]
		}
		return z
	}
	return nil
}

func (m *TransactionType) GetBinOutputs() []types.TxOutputBinTyper {
	if m != nil {
		l := len(m.BinOutputs)
		z := make([]types.TxOutputBinTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.BinOutputs[i]
		}
		return z
	}
	return nil
}

func (m *TransactionType) GetOutputs() []types.TxOutputTyper {
	if m != nil {
		l := len(m.Outputs)
		z := make([]types.TxOutputTyper, l)
		for i := 0; i < l; i++ {
			z[i] = m.Outputs[i]
		}
		return z
	}
	return nil
}

func (m *TransactionType) GetLockTime() uint32 {
	if m != nil && m.LockTime != nil {
		return *m.LockTime
	}
	return 0
}

func (m *TransactionType) GetInputsCnt() uint32 {
	if m != nil && m.InputsCnt != nil {
		return *m.InputsCnt
	}
	return 0
}

func (m *TransactionType) GetOutputsCnt() uint32 {
	if m != nil && m.OutputsCnt != nil {
		return *m.OutputsCnt
	}
	return 0
}

func (m *TransactionType) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *TransactionType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

// *
// Structure representing request details
// @used_in TxRequest
type TxRequestDetailsType struct {
	RequestIndex     *uint32 `protobuf:"varint,1,opt,name=request_index,json=requestIndex" json:"request_index,omitempty"`
	TxHash           []byte  `protobuf:"bytes,2,opt,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	ExtraDataLen     *uint32 `protobuf:"varint,3,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	ExtraDataOffset  *uint32 `protobuf:"varint,4,opt,name=extra_data_offset,json=extraDataOffset" json:"extra_data_offset,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxRequestDetailsType) Reset()                    { *m = TxRequestDetailsType{} }
func (m *TxRequestDetailsType) String() string            { return proto.CompactTextString(m) }
func (*TxRequestDetailsType) ProtoMessage()               {}
func (*TxRequestDetailsType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TxRequestDetailsType) GetRequestIndex() uint32 {
	if m != nil && m.RequestIndex != nil {
		return *m.RequestIndex
	}
	return 0
}

func (m *TxRequestDetailsType) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TxRequestDetailsType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

func (m *TxRequestDetailsType) GetExtraDataOffset() uint32 {
	if m != nil && m.ExtraDataOffset != nil {
		return *m.ExtraDataOffset
	}
	return 0
}

// *
// Structure representing serialized data
// @used_in TxRequest
type TxRequestSerializedType struct {
	SignatureIndex   *uint32 `protobuf:"varint,1,opt,name=signature_index,json=signatureIndex" json:"signature_index,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	SerializedTx     []byte  `protobuf:"bytes,3,opt,name=serialized_tx,json=serializedTx" json:"serialized_tx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxRequestSerializedType) Reset()                    { *m = TxRequestSerializedType{} }
func (m *TxRequestSerializedType) String() string            { return proto.CompactTextString(m) }
func (*TxRequestSerializedType) ProtoMessage()               {}
func (*TxRequestSerializedType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TxRequestSerializedType) GetSignatureIndex() uint32 {
	if m != nil && m.SignatureIndex != nil {
		return *m.SignatureIndex
	}
	return 0
}

func (m *TxRequestSerializedType) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TxRequestSerializedType) GetSerializedTx() []byte {
	if m != nil {
		return m.SerializedTx
	}
	return nil
}

// *
// Structure representing identity data
// @used_in IdentityType
type IdentityType struct {
	Proto            *string `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	User             *string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Host             *string `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port             *string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	Path             *string `protobuf:"bytes,5,opt,name=path" json:"path,omitempty"`
	Index            *uint32 `protobuf:"varint,6,opt,name=index,def=0" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IdentityType) Reset()                    { *m = IdentityType{} }
func (m *IdentityType) String() string            { return proto.CompactTextString(m) }
func (*IdentityType) ProtoMessage()               {}
func (*IdentityType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

const Default_IdentityType_Index uint32 = 0

func (m *IdentityType) GetProto() string {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return ""
}

func (m *IdentityType) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *IdentityType) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *IdentityType) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *IdentityType) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *IdentityType) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_IdentityType_Index
}

var E_WireIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "wire_in",
	Tag:           "varint,50002,opt,name=wire_in,json=wireIn",
	Filename:      "types.proto",
}

var E_WireOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "wire_out",
	Tag:           "varint,50003,opt,name=wire_out,json=wireOut",
	Filename:      "types.proto",
}

var E_WireDebugIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50004,
	Name:          "wire_debug_in",
	Tag:           "varint,50004,opt,name=wire_debug_in,json=wireDebugIn",
	Filename:      "types.proto",
}

var E_WireDebugOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50005,
	Name:          "wire_debug_out",
	Tag:           "varint,50005,opt,name=wire_debug_out,json=wireDebugOut",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*HDNodeType)(nil), "trezorHDNodeType")
	proto.RegisterType((*HDNodePathType)(nil), "trezorHDNodePathType")
	proto.RegisterType((*CoinType)(nil), "trezorCoinType")
	proto.RegisterType((*MultisigRedeemScriptType)(nil), "trezorMultisigRedeemScriptType")
	proto.RegisterType((*TxInputType)(nil), "trezorTxInputType")
	proto.RegisterType((*TxOutputType)(nil), "trezorTxOutputType")
	proto.RegisterType((*TxOutputBinType)(nil), "trezorTxOutputBinType")
	proto.RegisterType((*TransactionType)(nil), "trezorTransactionType")
	proto.RegisterType((*TxRequestDetailsType)(nil), "trezorTxRequestDetailsType")
	proto.RegisterType((*TxRequestSerializedType)(nil), "trezorTxRequestSerializedType")
	proto.RegisterType((*IdentityType)(nil), "trezorIdentityType")
	proto.RegisterEnum("trezorFailureType", FailureType_name, FailureType_value)
	proto.RegisterEnum("trezorOutputScriptType", OutputScriptType_name, OutputScriptType_value)
	proto.RegisterEnum("trezorInputScriptType", InputScriptType_name, InputScriptType_value)
	proto.RegisterEnum("trezorRequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("trezorButtonRequestType", ButtonRequestType_name, ButtonRequestType_value)
	proto.RegisterEnum("trezorPinMatrixRequestType", PinMatrixRequestType_name, PinMatrixRequestType_value)
	proto.RegisterEnum("trezorRecoveryDeviceType", RecoveryDeviceType_name, RecoveryDeviceType_value)
	proto.RegisterEnum("trezorWordRequestType", WordRequestType_name, WordRequestType_value)
	proto.RegisterExtension(E_WireIn)
	proto.RegisterExtension(E_WireOut)
	proto.RegisterExtension(E_WireDebugIn)
	proto.RegisterExtension(E_WireDebugOut)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x6e, 0x1a, 0xcb,
	0x1d, 0xcf, 0x02, 0xb6, 0xe1, 0x0f, 0x98, 0xf1, 0x24, 0x27, 0x26, 0x27, 0xc9, 0x09, 0x21, 0x69,
	0x8f, 0x6b, 0xe9, 0x70, 0x12, 0x74, 0x92, 0x2a, 0x56, 0xd5, 0x8a, 0x18, 0x7c, 0x8c, 0x92, 0x00,
	0x1a, 0xd6, 0x8d, 0xdb, 0x9b, 0xd5, 0xb2, 0x3b, 0x66, 0x47, 0x5e, 0x66, 0xe9, 0xec, 0xac, 0x83,
	0xcf, 0x4d, 0xaf, 0xda, 0x5e, 0xf5, 0x35, 0xfa, 0x16, 0x95, 0xfa, 0x02, 0x55, 0xa5, 0x7e, 0xa8,
	0x97, 0x7d, 0x83, 0x3e, 0x43, 0x35, 0x33, 0xbb, 0x18, 0xec, 0xa4, 0xca, 0x1d, 0xf3, 0xfb, 0xfd,
	0xbf, 0x3f, 0x66, 0x58, 0x28, 0xcb, 0xcb, 0x39, 0x8d, 0x5b, 0x73, 0x11, 0xc9, 0xe8, 0xcb, 0xc6,
	0x34, 0x8a, 0xa6, 0x21, 0xfd, 0x56, 0x9f, 0x26, 0xc9, 0xd9, 0xb7, 0x3e, 0x8d, 0x3d, 0xc1, 0xe6,
	0x32, 0x12, 0x46, 0xa2, 0xf9, 0x17, 0x0b, 0xe0, 0xb8, 0x3b, 0x88, 0x7c, 0x6a, 0x5f, 0xce, 0x29,
	0xbe, 0x03, 0x1b, 0x3e, 0x9d, 0xcb, 0xa0, 0x6e, 0x35, 0x72, 0x7b, 0x55, 0x62, 0x0e, 0xb8, 0x01,
	0xe5, 0x33, 0xc6, 0xa7, 0x54, 0xcc, 0x05, 0xe3, 0xb2, 0x9e, 0xd3, 0xdc, 0x2a, 0x84, 0xef, 0x43,
	0xc9, 0x0b, 0x58, 0xe8, 0x3b, 0x3c, 0x99, 0xd5, 0xf3, 0x9a, 0x2f, 0x6a, 0x60, 0x90, 0xcc, 0xf0,
	0x43, 0x00, 0x2f, 0x70, 0x19, 0x77, 0xbc, 0xc8, 0xa7, 0xf5, 0x42, 0x23, 0xb7, 0x57, 0x21, 0x25,
	0x8d, 0x1c, 0x46, 0x3e, 0xc5, 0x8f, 0xa0, 0x3c, 0x17, 0xec, 0xc2, 0x95, 0xd4, 0x39, 0xa7, 0x97,
	0xf5, 0x8d, 0x86, 0xb5, 0x57, 0x21, 0x90, 0x42, 0x6f, 0xe8, 0xa5, 0xd2, 0x9f, 0x27, 0x93, 0x90,
	0x79, 0x9a, 0xdf, 0xd4, 0x7c, 0xc9, 0x20, 0x6f, 0xe8, 0x65, 0x73, 0x00, 0xdb, 0x26, 0x83, 0x91,
	0x2b, 0x03, 0x9d, 0xc5, 0x23, 0x28, 0x70, 0xe5, 0x4a, 0x25, 0x51, 0x6e, 0x97, 0x5b, 0x57, 0x09,
	0x12, 0x4d, 0xa8, 0x70, 0x5d, 0xdf, 0x17, 0x34, 0x8e, 0x1d, 0x5e, 0xcf, 0x35, 0xf2, 0x2a, 0xdc,
	0x14, 0x18, 0x34, 0xff, 0x9d, 0x83, 0xe2, 0x61, 0xc4, 0xb8, 0x36, 0xa5, 0x12, 0x8b, 0x18, 0x77,
	0xb8, 0x3b, 0x53, 0xf6, 0xac, 0xbd, 0x12, 0x29, 0x2a, 0x60, 0xe0, 0xce, 0x28, 0x7e, 0x02, 0x55,
	0x4d, 0xc6, 0x41, 0x24, 0xa4, 0x97, 0xa8, 0xca, 0x28, 0x81, 0x8a, 0x02, 0xc7, 0x29, 0x86, 0x9f,
	0x42, 0x25, 0xf3, 0xa5, 0x5a, 0x53, 0xcf, 0x37, 0xac, 0xbd, 0xea, 0x81, 0xf5, 0x8c, 0x94, 0x53,
	0x38, 0xf3, 0x33, 0x73, 0x17, 0x67, 0x94, 0x3a, 0xe7, 0x93, 0x7a, 0xa1, 0x61, 0xed, 0x15, 0x48,
	0xd1, 0x00, 0x6f, 0x26, 0xf8, 0x1b, 0xd8, 0x59, 0x35, 0xe1, 0xcc, 0xdb, 0x71, 0xa0, 0xeb, 0x54,
	0x3d, 0xb0, 0x5e, 0x90, 0xda, 0x8a, 0x9d, 0x51, 0x3b, 0x0e, 0xf0, 0x73, 0xb8, 0x7d, 0x4d, 0xfc,
	0xc3, 0xfc, 0x3c, 0xd0, 0x85, 0xab, 0x1e, 0x58, 0x2f, 0xc9, 0xce, 0x9a, 0x82, 0xe2, 0xf0, 0x33,
	0xc0, 0xd7, 0x55, 0xe2, 0xa0, 0xbe, 0xa5, 0x35, 0x72, 0xcf, 0x9f, 0x11, 0xb4, 0xae, 0x12, 0x07,
	0xb8, 0x0d, 0x5f, 0xc4, 0x6c, 0xca, 0xa9, 0xef, 0xcc, 0x68, 0x1c, 0xbb, 0x53, 0xea, 0x04, 0xd4,
	0xf5, 0xa9, 0xa8, 0x17, 0x75, 0x0d, 0x6e, 0x1b, 0xf2, 0x9d, 0xe1, 0x8e, 0x35, 0xd5, 0x8c, 0xa1,
	0xfe, 0x2e, 0x09, 0x25, 0x8b, 0xd9, 0x94, 0x50, 0x9f, 0xd2, 0xd9, 0x58, 0x0f, 0xa3, 0x2e, 0xc0,
	0x4f, 0x60, 0x6b, 0x9e, 0x4c, 0xce, 0xe9, 0x65, 0x5c, 0xb7, 0x1a, 0xf9, 0xbd, 0x72, 0xbb, 0xd6,
	0x5a, 0xef, 0x2a, 0xc9, 0x78, 0xfc, 0x15, 0x80, 0xb2, 0xee, 0xca, 0x44, 0xd0, 0x58, 0xb7, 0xaf,
	0x42, 0x56, 0x10, 0x5c, 0x01, 0x6b, 0x66, 0xca, 0x4c, 0xac, 0x59, 0xf3, 0xcf, 0x39, 0x28, 0xdb,
	0x8b, 0x3e, 0x9f, 0x27, 0x32, 0xab, 0xf4, 0x55, 0xef, 0xad, 0xf5, 0xde, 0x2b, 0x72, 0x2e, 0xe8,
	0x85, 0x13, 0xb8, 0x71, 0xa0, 0xe7, 0xbc, 0x42, 0x8a, 0x0a, 0x38, 0x76, 0xe3, 0x40, 0xcf, 0xa1,
	0x22, 0x19, 0xf7, 0xe9, 0x22, 0x9d, 0x72, 0x2d, 0xde, 0x57, 0x80, 0xa2, 0xcd, 0x72, 0x39, 0x31,
	0x9b, 0xea, 0x1e, 0x56, 0x48, 0xc9, 0x20, 0x63, 0x36, 0xc5, 0x3f, 0x86, 0x62, 0x4c, 0x7f, 0x93,
	0x50, 0xee, 0xd1, 0xb4, 0x77, 0xf0, 0x5d, 0xfb, 0xd5, 0x77, 0xaf, 0x5e, 0xfe, 0xb4, 0xfd, 0xea,
	0x05, 0x59, 0x72, 0xf8, 0x17, 0x50, 0x4e, 0xcd, 0xe8, 0x71, 0x51, 0x5d, 0xdb, 0x6e, 0xa3, 0x96,
	0x4e, 0xe0, 0xaa, 0x5e, 0x07, 0x95, 0xf1, 0xa8, 0x37, 0xe8, 0x76, 0xba, 0x5d, 0xd2, 0x1b, 0x8f,
	0x49, 0xea, 0x59, 0x27, 0xf8, 0x02, 0x8a, 0xb3, 0xb4, 0xca, 0xba, 0x83, 0xe5, 0xf6, 0xbd, 0xd6,
	0xa7, 0xca, 0x4e, 0x96, 0xa2, 0xf8, 0x2e, 0x6c, 0xba, 0xb3, 0x28, 0xe1, 0x52, 0x77, 0xb0, 0x40,
	0xd2, 0x53, 0xf3, 0xbf, 0x16, 0x54, 0xec, 0xc5, 0x30, 0x91, 0x59, 0x01, 0xeb, 0xb0, 0x95, 0xd6,
	0x2b, 0x5d, 0x88, 0xec, 0xf8, 0x7f, 0xd7, 0x6a, 0xc5, 0xbe, 0xaa, 0xdc, 0xd2, 0x3e, 0x6e, 0xaf,
	0xe7, 0xab, 0xae, 0x87, 0xed, 0xf6, 0x4e, 0xcb, 0x38, 0x5c, 0x89, 0xf4, 0x53, 0x29, 0x6e, 0x7c,
	0x7e, 0x8a, 0x4f, 0x61, 0x3b, 0x9a, 0x3b, 0x82, 0xca, 0x44, 0x70, 0xc7, 0x77, 0xa5, 0x9b, 0x5e,
	0x26, 0x95, 0x68, 0x4e, 0x34, 0xd8, 0x75, 0xa5, 0xdb, 0x1c, 0x40, 0x2d, 0xcb, 0xf7, 0x75, 0x7a,
	0x0b, 0x5c, 0xc5, 0x6e, 0xad, 0xc5, 0xfe, 0x04, 0xaa, 0x69, 0xec, 0x66, 0x36, 0xd3, 0x91, 0xa9,
	0x18, 0x70, 0xa4, 0xb1, 0xe6, 0xdf, 0x72, 0x50, 0xb3, 0x85, 0xcb, 0x63, 0xd7, 0x93, 0x2c, 0xe2,
	0x59, 0x0d, 0x2f, 0xa8, 0x88, 0x59, 0xc4, 0x75, 0x0d, 0xab, 0x24, 0x3b, 0xe2, 0xa7, 0xb0, 0xc9,
	0x54, 0xab, 0xcd, 0x60, 0x97, 0xdb, 0x95, 0xd6, 0xca, 0xf0, 0x92, 0x94, 0xc3, 0xcf, 0xa1, 0x3c,
	0x61, 0xdc, 0x89, 0x74, 0x94, 0x71, 0x3d, 0xaf, 0x45, 0x51, 0xeb, 0x5a, 0xdc, 0x04, 0x26, 0x8c,
	0x1b, 0x24, 0xc6, 0x5f, 0xc3, 0x56, 0x26, 0xbe, 0xa1, 0xc5, 0xab, 0xad, 0xd5, 0xb6, 0x92, 0x8c,
	0x55, 0x5d, 0x0c, 0x23, 0xef, 0xdc, 0x91, 0x6c, 0x46, 0xf5, 0x18, 0x57, 0x49, 0x51, 0x01, 0x36,
	0x9b, 0x51, 0x35, 0xe4, 0x26, 0x04, 0xc7, 0xe3, 0xd2, 0x5c, 0x29, 0xa4, 0x64, 0x90, 0x43, 0x2e,
	0xd5, 0x5d, 0x9e, 0x9a, 0xd1, 0xbc, 0xbe, 0x40, 0x08, 0xa4, 0x90, 0x12, 0x78, 0x08, 0x40, 0x17,
	0x52, 0xb8, 0xa6, 0xfc, 0x45, 0xb3, 0x24, 0x1a, 0x51, 0xb5, 0x57, 0x1d, 0xba, 0xa2, 0x9d, 0x90,
	0xf2, 0x7a, 0x49, 0x9b, 0xa8, 0x2c, 0x45, 0xde, 0x52, 0xde, 0xfc, 0x93, 0x05, 0x77, 0xec, 0x05,
	0x51, 0x1b, 0x13, 0xcb, 0x2e, 0x95, 0x2e, 0x0b, 0xcd, 0x2d, 0xfa, 0x04, 0xaa, 0xc2, 0xa0, 0xe9,
	0x92, 0x9a, 0xe2, 0x56, 0x52, 0xd0, 0xec, 0xe9, 0x2e, 0x6c, 0xc9, 0x45, 0xb6, 0xe1, 0xca, 0xff,
	0xa6, 0x5c, 0xe8, 0xfd, 0xbe, 0xe9, 0x3c, 0x7f, 0xd3, 0x39, 0xde, 0x87, 0x9d, 0x15, 0xa9, 0xe8,
	0xec, 0x2c, 0xa6, 0x32, 0x2d, 0x53, 0x6d, 0x29, 0x38, 0xd4, 0x70, 0xf3, 0x77, 0x16, 0xec, 0x2e,
	0x03, 0x1d, 0x53, 0xc1, 0xdc, 0x90, 0xfd, 0x40, 0x7d, 0x1d, 0xeb, 0xd7, 0x50, 0x5b, 0xde, 0x59,
	0x6b, 0xd1, 0x6e, 0x2f, 0x61, 0x13, 0xef, 0x03, 0x28, 0x2d, 0x91, 0x34, 0xe2, 0x2b, 0x40, 0x8f,
	0xe0, 0xd2, 0xb0, 0x23, 0x17, 0x3a, 0x66, 0x35, 0x82, 0x57, 0xde, 0x16, 0xcd, 0x3f, 0x5a, 0x50,
	0xe9, 0xfb, 0x94, 0x4b, 0x26, 0x2f, 0xb3, 0x77, 0x5e, 0xbf, 0xff, 0xe9, 0x06, 0x9b, 0x03, 0xc6,
	0x50, 0x48, 0x62, 0x2a, 0xd2, 0x67, 0x4c, 0xff, 0x56, 0x58, 0x10, 0xc5, 0x52, 0x9b, 0x2d, 0x11,
	0xfd, 0x5b, 0x61, 0xf3, 0x48, 0x98, 0xac, 0x4b, 0x44, 0xff, 0xd6, 0x98, 0x2b, 0xcd, 0xb3, 0xa4,
	0x30, 0x57, 0x06, 0x78, 0x17, 0x36, 0x4c, 0x62, 0x9b, 0xd9, 0x9b, 0x67, 0xce, 0xfb, 0x7f, 0xcd,
	0x41, 0xf9, 0xc8, 0x65, 0x61, 0x22, 0xcc, 0xdf, 0x8e, 0x87, 0x70, 0x2f, 0x3d, 0x3a, 0x27, 0x9c,
	0x2e, 0xe6, 0xd4, 0x93, 0xcb, 0xb7, 0x03, 0x59, 0xf8, 0x4b, 0xb8, 0x9b, 0xd1, 0xaf, 0x13, 0x29,
	0x23, 0xde, 0x4b, 0x45, 0x50, 0x0e, 0xef, 0xc2, 0xed, 0x8c, 0x1b, 0x5f, 0x72, 0xe9, 0x2e, 0x7a,
	0x42, 0x44, 0x02, 0xe5, 0xf1, 0x7d, 0xd8, 0xcd, 0x88, 0x8e, 0x5e, 0xbc, 0x43, 0x97, 0x7b, 0x34,
	0x0c, 0xa9, 0x8f, 0x0a, 0xab, 0x5a, 0x23, 0x76, 0x65, 0x6e, 0x03, 0xd7, 0xe1, 0xce, 0x0a, 0x71,
	0xa5, 0xb2, 0x89, 0xef, 0x02, 0x5e, 0x61, 0xfa, 0xfc, 0xc2, 0x0d, 0x99, 0x8f, 0xb6, 0xf0, 0x03,
	0xa8, 0x67, 0x78, 0x0a, 0x8e, 0xb3, 0xe6, 0xa0, 0x22, 0xde, 0x81, 0x6a, 0xc6, 0x0e, 0x65, 0x40,
	0x05, 0x2a, 0xad, 0x66, 0x33, 0x88, 0x64, 0x8f, 0x47, 0xc9, 0x34, 0x38, 0x4a, 0xb8, 0x1f, 0x23,
	0xb8, 0xc6, 0xf5, 0x39, 0x93, 0x69, 0x13, 0x51, 0x19, 0xdf, 0x83, 0x2f, 0x32, 0xee, 0x88, 0x89,
	0xd9, 0x07, 0x57, 0x50, 0x93, 0xab, 0xb7, 0xff, 0x07, 0x0b, 0xd0, 0xf5, 0x0b, 0x13, 0x23, 0xa8,
	0x8c, 0x3a, 0xbf, 0xb2, 0x87, 0xe9, 0x1b, 0x81, 0x6e, 0xe1, 0xdb, 0x50, 0xd3, 0xc8, 0xf8, 0x90,
	0xf4, 0x47, 0xf6, 0x71, 0x67, 0x7c, 0x8c, 0x2c, 0x15, 0xa1, 0x06, 0xdf, 0x9d, 0xbc, 0xb5, 0xfb,
	0xe3, 0xfe, 0xf7, 0x28, 0xb7, 0x84, 0x86, 0x23, 0xd2, 0xb3, 0x4f, 0xc8, 0x00, 0xe5, 0x97, 0xc6,
	0xde, 0xf7, 0xed, 0x81, 0x32, 0x56, 0xc0, 0x77, 0x00, 0x69, 0x64, 0xd4, 0x1e, 0x1f, 0x67, 0xe8,
	0xc6, 0x7e, 0x08, 0xb5, 0x6b, 0x2f, 0x95, 0x52, 0x5d, 0x7d, 0xab, 0xd0, 0x2d, 0x65, 0x5f, 0x23,
	0x4b, 0x97, 0x16, 0xae, 0x40, 0xb1, 0x77, 0x6a, 0xf7, 0xc8, 0xa0, 0xf3, 0x16, 0xe5, 0x96, 0x2a,
	0x99, 0xdd, 0xbc, 0xf2, 0xa6, 0x91, 0x55, 0x6f, 0x85, 0xfd, 0x13, 0x28, 0xa7, 0xcb, 0xa5, 0x3d,
	0x95, 0x61, 0xcb, 0x3e, 0xed, 0x0f, 0x46, 0x27, 0x36, 0xba, 0xa5, 0x2c, 0xda, 0xa7, 0xc3, 0x13,
	0x5b, 0x9d, 0x2c, 0x0c, 0xb0, 0x69, 0x9f, 0xbe, 0xeb, 0xd9, 0x1d, 0x94, 0xc3, 0xdb, 0x00, 0xf6,
	0xe9, 0x51, 0x7f, 0xd0, 0x1f, 0x1f, 0xf7, 0xba, 0x28, 0x8f, 0x6b, 0x50, 0xb6, 0x4f, 0x7b, 0xa7,
	0x36, 0xe9, 0x74, 0x3b, 0x76, 0x07, 0x15, 0xf6, 0xff, 0x93, 0x83, 0x1d, 0x33, 0x68, 0xab, 0xd6,
	0x77, 0xe1, 0xf6, 0x1a, 0x98, 0x36, 0xd4, 0xc2, 0x4d, 0xf8, 0x6a, 0x9d, 0x38, 0xa2, 0x74, 0x78,
	0x41, 0x85, 0x1d, 0x08, 0x1a, 0x07, 0x51, 0xa8, 0xc6, 0xf4, 0x11, 0xdc, 0x5f, 0x97, 0x39, 0x8c,
	0xf8, 0x19, 0x13, 0x33, 0xd3, 0x35, 0x94, 0x57, 0x2b, 0xb0, 0x2e, 0x40, 0x68, 0x4c, 0x65, 0x97,
	0x5e, 0x30, 0x8f, 0xa2, 0xc2, 0x4d, 0x3a, 0xd5, 0x7f, 0x1f, 0x09, 0x35, 0xb6, 0x0f, 0xa0, 0xbe,
	0x4e, 0xbf, 0x67, 0x73, 0x9a, 0x2a, 0x6f, 0xde, 0x54, 0x1e, 0x89, 0x48, 0x52, 0x4f, 0x1e, 0xba,
	0x61, 0x88, 0xb6, 0xd4, 0xcc, 0xaf, 0xd3, 0x6a, 0x80, 0xed, 0x05, 0x2a, 0xde, 0x8c, 0x3a, 0x1b,
	0xbc, 0xc3, 0x80, 0x7a, 0xe7, 0xa8, 0xa4, 0x66, 0x72, 0x5d, 0xa0, 0x63, 0x9e, 0x7b, 0x04, 0x6a,
	0xff, 0xae, 0x39, 0xcd, 0xfe, 0xb1, 0xa3, 0xf2, 0xfe, 0x6f, 0xe1, 0xce, 0x88, 0xf1, 0x77, 0xae,
	0x14, 0x6c, 0xb1, 0x5a, 0xe3, 0x06, 0x3c, 0xf8, 0x18, 0xee, 0x1c, 0x26, 0x42, 0x50, 0x2e, 0x91,
	0x85, 0x1f, 0xc3, 0xc3, 0x8f, 0x4a, 0x0c, 0xe8, 0x87, 0x23, 0x26, 0x62, 0x89, 0x72, 0xaa, 0x1f,
	0x9f, 0x12, 0x19, 0x53, 0x2f, 0xe2, 0x3e, 0xca, 0xef, 0xff, 0x1a, 0x30, 0xa1, 0x5e, 0x74, 0x41,
	0xc5, 0xa5, 0x29, 0x93, 0x76, 0xff, 0x23, 0x78, 0x7c, 0x13, 0x75, 0xc6, 0x9e, 0x70, 0x67, 0x93,
	0x90, 0xfa, 0xaa, 0xd8, 0x31, 0xba, 0xa5, 0xea, 0xf9, 0x11, 0x31, 0xe3, 0x10, 0x59, 0xfb, 0x67,
	0x50, 0x53, 0x92, 0xab, 0x79, 0xdd, 0x83, 0x2f, 0xae, 0x41, 0xce, 0x28, 0x74, 0x19, 0x47, 0xb7,
	0x54, 0x9d, 0xae, 0x53, 0xc6, 0xd2, 0x2b, 0x64, 0x7d, 0x9a, 0x7c, 0x89, 0x72, 0x07, 0x3f, 0x83,
	0xad, 0x0f, 0x4c, 0x3f, 0x1e, 0xf8, 0x71, 0xcb, 0x7c, 0xe9, 0xb5, 0xb2, 0x2f, 0xbd, 0x56, 0x8f,
	0x27, 0xb3, 0x5f, 0xba, 0x61, 0x42, 0x87, 0x73, 0x75, 0xf9, 0xc5, 0xf5, 0xbf, 0xff, 0x5e, 0x5d,
	0xe1, 0x45, 0xb2, 0xa9, 0x74, 0xfa, 0xfc, 0xe0, 0xe7, 0x50, 0xd4, 0xda, 0x51, 0x22, 0x3f, 0x47,
	0xfd, 0x1f, 0xa9, 0xba, 0x76, 0x39, 0x4c, 0xe4, 0xc1, 0xf7, 0x50, 0xd5, 0xfa, 0x3e, 0x9d, 0x24,
	0xd3, 0xcf, 0x8c, 0xe1, 0x9f, 0xa9, 0x91, 0xb2, 0xd2, 0xec, 0x2a, 0xc5, 0x3e, 0x3f, 0xe8, 0xc3,
	0xf6, 0x8a, 0xa1, 0xcf, 0x0c, 0xe7, 0x5f, 0xa9, 0xa5, 0xca, 0xd2, 0xd2, 0x30, 0x91, 0xaf, 0xbf,
	0x81, 0x47, 0x5e, 0x34, 0x6b, 0xc5, 0xae, 0x8c, 0xe2, 0x80, 0x85, 0xee, 0x24, 0x6e, 0x49, 0x41,
	0x7f, 0xc8, 0xbe, 0x76, 0x27, 0xc9, 0xd9, 0x6b, 0xb0, 0x35, 0xa0, 0x4a, 0xf9, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0xc7, 0x6d, 0x47, 0x2c, 0x0f, 0x00, 0x00,
}

/* ADDED CONTENT HERE */

type OutputAddressType int32

func (z *TxRequestDetailsType) SetExtraDataOffset(x *uint32) {
	z.ExtraDataOffset = x
}

func (z *TxRequestDetailsType) SetRequestIndex(x *uint32) {
	z.RequestIndex = x
}

func (z *TxRequestDetailsType) SetTxHash(x []byte) {
	z.TxHash = x
}

func (z *TxRequestDetailsType) SetExtraDataLen(x *uint32) {
	z.ExtraDataLen = x
}

func (z *TxRequestSerializedType) SetSignatureIndex(x *uint32) {
	z.SignatureIndex = x
}

func (z *TxRequestSerializedType) SetSignature(x []byte) {
	z.Signature = x
}

func (z *TxRequestSerializedType) SetSerializedTx(x []byte) {
	z.SerializedTx = x
}

func (z *IdentityType) SetProto(x *string) {
	z.Proto = x
}

func (z *IdentityType) SetUser(x *string) {
	z.User = x
}

func (z *IdentityType) SetHost(x *string) {
	z.Host = x
}

func (z *IdentityType) SetPort(x *string) {
	z.Port = x
}

func (z *IdentityType) SetPath(x *string) {
	z.Path = x
}

func (z *IdentityType) SetIndex(x *uint32) {
	z.Index = x
}

func (z *MultisigRedeemScriptType) SetPubkeys(x []types.HDNodePathTyper) {
	l := len(x)
	xx := make([]*HDNodePathType, l)
	zx := make([]HDNodePathType, l)
	for i := 0; i < l; i++ {
		zx[i] = HDNodePathTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.Pubkeys = xx
}

func (z *MultisigRedeemScriptType) SetSignatures(x [][]byte) {
	z.Signatures = x
}

func (z *MultisigRedeemScriptType) SetM(x *uint32) {
	z.M = x
}

func (z *TxInputType) SetScriptSig(x []byte) {
	z.ScriptSig = x
}

func (z *TxInputType) SetSequence(x *uint32) {
	z.Sequence = x
}

func (z *TxInputType) SetScriptType(x types.InputScriptTyper) {
	zx := InputScriptTyper2Type(x)
	z.ScriptType = &zx
}

func (z *TxInputType) SetMultisig(x types.MultisigRedeemScriptTyper) {
	zx := MultisigRedeemScriptTyper2Type(x)
	z.Multisig = &zx
}

func (z *TxInputType) SetAmount(x *uint64) {
	z.Amount = x
}

func (z *TxInputType) SetAddressN(x []uint32) {
	z.AddressN = x
}

func (z *TxInputType) SetPrevHash(x []byte) {
	z.PrevHash = x
}

func (z *TxInputType) SetPrevIndex(x *uint32) {
	z.PrevIndex = x
}

func (z *TxOutputType) SetScriptType(x types.OutputScriptTyper) {
	zx := OutputScriptTyper2Type(x)
	z.ScriptType = &zx
}

func (z *TxOutputType) SetMultisig(x types.MultisigRedeemScriptTyper) {
	zx := MultisigRedeemScriptTyper2Type(x)
	z.Multisig = &zx
}

func (z *TxOutputType) SetOpReturnData(x []byte) {
	z.OpReturnData = x
}

func (z *TxOutputType) SetAddress(x *string) {
	z.Address = x
}

func (z *TxOutputType) SetAddressN(x []uint32) {
	z.AddressN = x
}

func (z *TxOutputType) SetAmount(x *uint64) {
	z.Amount = x
}

func (z *TxOutputBinType) SetAmount(x *uint64) {
	z.Amount = x
}

func (z *TxOutputBinType) SetScriptPubkey(x []byte) {
	z.ScriptPubkey = x
}

func (z *TransactionType) SetOutputs(x []types.TxOutputTyper) {
	l := len(x)
	xx := make([]*TxOutputType, l)
	zx := make([]TxOutputType, l)
	for i := 0; i < l; i++ {
		zx[i] = TxOutputTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.Outputs = xx
}

func (z *TransactionType) SetLockTime(x *uint32) {
	z.LockTime = x
}

func (z *TransactionType) SetExtraData(x []byte) {
	z.ExtraData = x
}

func (z *TransactionType) SetInputsCnt(x *uint32) {
	z.InputsCnt = x
}

func (z *TransactionType) SetOutputsCnt(x *uint32) {
	z.OutputsCnt = x
}

func (z *TransactionType) SetExtraDataLen(x *uint32) {
	z.ExtraDataLen = x
}

func (z *TransactionType) SetVersion(x *uint32) {
	z.Version = x
}

func (z *TransactionType) SetInputs(x []types.TxInputTyper) {
	l := len(x)
	xx := make([]*TxInputType, l)
	zx := make([]TxInputType, l)
	for i := 0; i < l; i++ {
		zx[i] = TxInputTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.Inputs = xx
}

func (z *TransactionType) SetBinOutputs(x []types.TxOutputBinTyper) {
	l := len(x)
	xx := make([]*TxOutputBinType, l)
	zx := make([]TxOutputBinType, l)
	for i := 0; i < l; i++ {
		zx[i] = TxOutputBinTyper2Type(x[i])
		xx[i] = &zx[i]
	}
	z.BinOutputs = xx
}

func (z *HDNodeType) SetPublicKey(x []byte) {
	z.PublicKey = x
}

func (z *HDNodeType) SetDepth(x *uint32) {
	z.Depth = x
}

func (z *HDNodeType) SetFingerprint(x *uint32) {
	z.Fingerprint = x
}

func (z *HDNodeType) SetChildNum(x *uint32) {
	z.ChildNum = x
}

func (z *HDNodeType) SetChainCode(x []byte) {
	z.ChainCode = x
}

func (z *HDNodeType) SetPrivateKey(x []byte) {
	z.PrivateKey = x
}

func (z *HDNodePathType) SetNode(x types.HDNodeTyper) {
	zx := HDNodeTyper2Type(x)
	z.Node = &zx
}

func (z *HDNodePathType) SetAddressN(x []uint32) {
	z.AddressN = x
}

func (z *CoinType) SetMaxfeeKb(x *uint64) {
	z.MaxfeeKb = x
}

func (z *CoinType) SetAddressTypeP2Sh(x *uint32) {
	z.AddressTypeP2Sh = x
}

func (z *CoinType) SetAddressTypeP2Wpkh(x *uint32) {
	z.AddressTypeP2Wpkh = x
}

func (z *CoinType) SetAddressTypeP2Wsh(x *uint32) {
	z.AddressTypeP2Wsh = x
}

func (z *CoinType) SetSignedMessageHeader(x *string) {
	z.SignedMessageHeader = x
}

func (z *CoinType) SetCoinName(x *string) {
	z.CoinName = x
}

func (z *CoinType) SetCoinShortcut(x *string) {
	z.CoinShortcut = x
}

func (z *CoinType) SetAddressType(x *uint32) {
	z.AddressType = x
}

func (*ExchangeType) SetWithdrawalCoinName(x *string) {
}

func (*ExchangeType) SetWithdrawalAddressN(x []uint32) {
}

func (*ExchangeType) SetReturnAddressN(x []uint32) {
}

func (*ExchangeType) SetSignedExchangeResponse(x *exchange.SignedExchangeResponse) {
}

func (*RawTransactionType) SetPayload(x []byte) {
}

func (*TxOutputType) SetExchangeType(x types.ExchangeTyper) {
}

func (*TxOutputType) SetAddressType(x types.OutputAddressTyper) {
}

func (*CoinType) SetBip44AccountPath(x *uint32) {
}

func (*PolicyType) SetPolicyName(x *string) {
}

func (*PolicyType) SetEnabled(x *bool) {
}

type PolicyType struct{}
type ExchangeType struct{}
type RawTransactionType struct{}

func (*RawTransactionType) GetPayload() []byte {
	var x []byte
	return x
}
func (*RawTransactionType) Reset() {}
func (*RawTransactionType) String() string {
	var x string
	return x
}
func (*RawTransactionType) ProtoMessage() {}
func (*CoinType) GetBip44AccountPath() uint32 {
	var x uint32
	return x
}
func (*PolicyType) Reset() {}
func (*PolicyType) String() string {
	var x string
	return x
}
func (*PolicyType) ProtoMessage() {}
func (*PolicyType) GetPolicyName() string {
	var x string
	return x
}
func (*PolicyType) GetEnabled() bool {
	var x bool
	return x
}
func (*OutputAddressType) String() string {
	var x string
	return x
}
func (*OutputAddressType) UnmarshalJSON(data []byte) error {
	var x error
	return x
}
func (*TxOutputType) GetExchangeType() types.ExchangeTyper {
	var x ExchangeType
	return &x
}
func (*TxOutputType) GetAddressType() types.OutputAddressTyper {
	var x OutputAddressType
	return &x
}
func (*ExchangeType) GetReturnAddressN() []uint32 {
	var x []uint32
	return x
}
func (*ExchangeType) Reset() {}
func (*ExchangeType) String() string {
	var x string
	return x
}
func (*ExchangeType) ProtoMessage() {}
func (*ExchangeType) GetSignedExchangeResponse() *exchange.SignedExchangeResponse {
	var x *exchange.SignedExchangeResponse
	return x
}
func (*ExchangeType) GetWithdrawalCoinName() string {
	var x string
	return x
}
func (*ExchangeType) GetWithdrawalAddressN() []uint32 {
	var x []uint32
	return x
}

type Getter struct{}

func (*Getter) GetTxRequestSerializedType() types.TxRequestSerializedTyper {
	var x TxRequestSerializedType
	return &x
}

func (*Getter) GetTxInputType() types.TxInputTyper {
	var x TxInputType
	return &x
}

func (*Getter) GetCoinType() types.CoinTyper {
	var x CoinType
	return &x
}

func (*Getter) GetHDNodeType() types.HDNodeTyper {
	var x HDNodeType
	return &x
}

func (*Getter) GetHDNodePathType() types.HDNodePathTyper {
	var x HDNodePathType
	return &x
}

func (*Getter) GetPolicyType() types.PolicyTyper {
	var x PolicyType
	return &x
}

func (*Getter) GetTxRequestDetailsType() types.TxRequestDetailsTyper {
	var x TxRequestDetailsType
	return &x
}

func (*Getter) GetIdentityType() types.IdentityTyper {
	var x IdentityType
	return &x
}

func (*Getter) GetTxOutputBinType() types.TxOutputBinTyper {
	var x TxOutputBinType
	return &x
}

func (*Getter) GetRawTransactionType() types.RawTransactionTyper {
	var x RawTransactionType
	return &x
}

func (*Getter) GetMultisigRedeemScriptType() types.MultisigRedeemScriptTyper {
	var x MultisigRedeemScriptType
	return &x
}

func (*Getter) GetTransactionType() types.TransactionTyper {
	var x TransactionType
	return &x
}

func (*Getter) GetExchangeType() types.ExchangeTyper {
	var x ExchangeType
	return &x
}

func (*Getter) GetTxOutputType() types.TxOutputTyper {
	var x TxOutputType
	return &x
}

func (*Getter) GetButtonRequestType() types.ButtonRequestTyper {
	var x ButtonRequestType
	return &x
}

func (*Getter) GetFailureType() types.FailureTyper {
	var x FailureType
	return &x
}

func (*Getter) GetInputScriptType() types.InputScriptTyper {
	var x InputScriptType
	return &x
}

func (*Getter) GetOutputAddressType() types.OutputAddressTyper {
	var x OutputAddressType
	return &x
}

func (*Getter) GetOutputScriptType() types.OutputScriptTyper {
	var x OutputScriptType
	return &x
}

func (*Getter) GetPinMatrixRequestType() types.PinMatrixRequestTyper {
	var x PinMatrixRequestType
	return &x
}

func (*Getter) GetRecoveryDeviceType() types.RecoveryDeviceTyper {
	var x RecoveryDeviceType
	return &x
}

func (*Getter) GetRequestType() types.RequestTyper {
	var x RequestType
	return &x
}

func (*Getter) GetWordRequestType() types.WordRequestTyper {
	var x WordRequestType
	return &x
}




func TxInputTyper2Type(x types.TxInputTyper) TxInputType {
	var z TxInputType
	x0 := x.GetScriptSig()
	z.ScriptSig = x0
	x1 := x.GetSequence()
	z.Sequence = &x1
	x2 := InputScriptTyper2Type(x.GetScriptType())
	z.ScriptType = &x2
	x3 := MultisigRedeemScriptTyper2Type(x.GetMultisig())
	z.Multisig = &x3
	x4 := x.GetAmount()
	z.Amount = &x4
	x5 := x.GetAddressN()
	z.AddressN = x5
	x6 := x.GetPrevHash()
	z.PrevHash = x6
	x7 := x.GetPrevIndex()
	z.PrevIndex = &x7
	return z
}

func TxOutputTyper2Type(x types.TxOutputTyper) TxOutputType {
	var z TxOutputType
	x0 := x.GetAddressN()
	z.AddressN = x0
	x1 := x.GetAmount()
	z.Amount = &x1
	x2 := OutputScriptTyper2Type(x.GetScriptType())
	z.ScriptType = &x2
	x3 := MultisigRedeemScriptTyper2Type(x.GetMultisig())
	z.Multisig = &x3
	x4 := x.GetOpReturnData()
	z.OpReturnData = x4
	x5 := x.GetAddress()
	z.Address = &x5
	return z
}

func TxRequestDetailsTyper2Type(x types.TxRequestDetailsTyper) TxRequestDetailsType {
	var z TxRequestDetailsType
	x0 := x.GetRequestIndex()
	z.RequestIndex = &x0
	x1 := x.GetTxHash()
	z.TxHash = x1
	x2 := x.GetExtraDataLen()
	z.ExtraDataLen = &x2
	x3 := x.GetExtraDataOffset()
	z.ExtraDataOffset = &x3
	return z
}

func TxRequestSerializedTyper2Type(x types.TxRequestSerializedTyper) TxRequestSerializedType {
	var z TxRequestSerializedType
	x0 := x.GetSignature()
	z.Signature = x0
	x1 := x.GetSerializedTx()
	z.SerializedTx = x1
	x2 := x.GetSignatureIndex()
	z.SignatureIndex = &x2
	return z
}

func IdentityTyper2Type(x types.IdentityTyper) IdentityType {
	var z IdentityType
	x0 := x.GetIndex()
	z.Index = &x0
	x1 := x.GetProto()
	z.Proto = &x1
	x2 := x.GetUser()
	z.User = &x2
	x3 := x.GetHost()
	z.Host = &x3
	x4 := x.GetPort()
	z.Port = &x4
	x5 := x.GetPath()
	z.Path = &x5
	return z
}

func MultisigRedeemScriptTyper2Type(x types.MultisigRedeemScriptTyper) MultisigRedeemScriptType {
	var z MultisigRedeemScriptType
	xx0 := x.GetPubkeys()
	l0 := len(xx0)
	x0 := make([]*HDNodePathType, l0)
	for k, v := range xx0 {
		xxx0 := HDNodePathTyper2Type(v)
		x0[k] = &xxx0
	}
	z.Pubkeys = x0
	x1 := x.GetSignatures()
	z.Signatures = x1
	x2 := x.GetM()
	z.M = &x2
	return z
}

func HDNodePathTyper2Type(x types.HDNodePathTyper) HDNodePathType {
	var z HDNodePathType
	x0 := HDNodeTyper2Type(x.GetNode())
	z.Node = &x0
	x1 := x.GetAddressN()
	z.AddressN = x1
	return z
}

func CoinTyper2Type(x types.CoinTyper) CoinType {
	var z CoinType
	x0 := x.GetAddressTypeP2Wsh()
	z.AddressTypeP2Wsh = &x0
	x1 := x.GetSignedMessageHeader()
	z.SignedMessageHeader = &x1
	x2 := x.GetCoinName()
	z.CoinName = &x2
	x3 := x.GetCoinShortcut()
	z.CoinShortcut = &x3
	x4 := x.GetAddressType()
	z.AddressType = &x4
	x5 := x.GetMaxfeeKb()
	z.MaxfeeKb = &x5
	x6 := x.GetAddressTypeP2Sh()
	z.AddressTypeP2Sh = &x6
	x7 := x.GetAddressTypeP2Wpkh()
	z.AddressTypeP2Wpkh = &x7
	return z
}

func TxOutputBinTyper2Type(x types.TxOutputBinTyper) TxOutputBinType {
	var z TxOutputBinType
	x0 := x.GetAmount()
	z.Amount = &x0
	x1 := x.GetScriptPubkey()
	z.ScriptPubkey = x1
	return z
}

func TransactionTyper2Type(x types.TransactionTyper) TransactionType {
	var z TransactionType
	x0 := x.GetInputsCnt()
	z.InputsCnt = &x0
	x1 := x.GetOutputsCnt()
	z.OutputsCnt = &x1
	x2 := x.GetExtraDataLen()
	z.ExtraDataLen = &x2
	x3 := x.GetVersion()
	z.Version = &x3
	xx4 := x.GetInputs()
	l4 := len(xx4)
	x4 := make([]*TxInputType, l4)
	for k, v := range xx4 {
		xxx4 := TxInputTyper2Type(v)
		x4[k] = &xxx4
	}
	z.Inputs = x4
	xx5 := x.GetBinOutputs()
	l5 := len(xx5)
	x5 := make([]*TxOutputBinType, l5)
	for k, v := range xx5 {
		xxx5 := TxOutputBinTyper2Type(v)
		x5[k] = &xxx5
	}
	z.BinOutputs = x5
	xx6 := x.GetOutputs()
	l6 := len(xx6)
	x6 := make([]*TxOutputType, l6)
	for k, v := range xx6 {
		xxx6 := TxOutputTyper2Type(v)
		x6[k] = &xxx6
	}
	z.Outputs = x6
	x7 := x.GetLockTime()
	z.LockTime = &x7
	x8 := x.GetExtraData()
	z.ExtraData = x8
	return z
}

func HDNodeTyper2Type(x types.HDNodeTyper) HDNodeType {
	var z HDNodeType
	x0 := x.GetFingerprint()
	z.Fingerprint = &x0
	x1 := x.GetChildNum()
	z.ChildNum = &x1
	x2 := x.GetChainCode()
	z.ChainCode = x2
	x3 := x.GetPrivateKey()
	z.PrivateKey = x3
	x4 := x.GetPublicKey()
	z.PublicKey = x4
	x5 := x.GetDepth()
	z.Depth = &x5
	return z
}

func RecoveryDeviceTyper2Type(x types.RecoveryDeviceTyper) RecoveryDeviceType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return RecoveryDeviceType(int32(tmp))
}

func WordRequestTyper2Type(x types.WordRequestTyper) WordRequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return WordRequestType(int32(tmp))
}

func FailureTyper2Type(x types.FailureTyper) FailureType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return FailureType(int32(tmp))
}

func OutputScriptTyper2Type(x types.OutputScriptTyper) OutputScriptType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return OutputScriptType(int32(tmp))
}

func InputScriptTyper2Type(x types.InputScriptTyper) InputScriptType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return InputScriptType(int32(tmp))
}

func RequestTyper2Type(x types.RequestTyper) RequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return RequestType(int32(tmp))
}

func ButtonRequestTyper2Type(x types.ButtonRequestTyper) ButtonRequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return ButtonRequestType(int32(tmp))
}

func PinMatrixRequestTyper2Type(x types.PinMatrixRequestTyper) PinMatrixRequestType {
	value := (x).String()
	tmp, _ := strconv.Atoi(value)
	return PinMatrixRequestType(int32(tmp))
}
